/* English layer for the plans. dict: German label → English (rooms, notes, legend, section, chips). Long texts by level/number in p12–p14. */
const PLAN_EN={dict:{
 // levels
 'Schnitt':'Section','Tiefgarage P2':'Parking garage P2','Ebene 111':'Level 111','Ebene 112':'Level 112','Ebene 110':'Level 110','Dach':'Roof',
 'Alle vertikalen Verbindungen auf einen Blick':'All vertical connections at a glance','Anlieferung, Frachtaufzug & VIP-Vorfahrt (Ausschnitt)':'Deliveries, freight elevator & VIP drop-off (detail)',
 'Penthouse · Gala-Ebene':'Penthouse · gala level','Penthouse · VIP-Lounge, Suite & Skycab-Lobby':'Penthouse · VIP lounge, suite & skycab lobby','Landeplattform, Glasdächer, Gondel & drei Wege nach unten':'Landing pad, glass roofs, gondola & three ways down','Tresorgeschoss · offiziell „technische Ebene“':'Vault level · officially a “technical floor”',
 'TIEFGARAGE P2 · ANLIEFERUNG (AUSSCHNITT)':'PARKING GARAGE P2 · DELIVERIES (DETAIL)','EBENE 111 · GALA-EBENE':'LEVEL 111 · GALA LEVEL','EBENE 112 · OBERE PENTHOUSE-EBENE':'LEVEL 112 · UPPER PENTHOUSE LEVEL','DACH · 112 STOCKWERKE ÜBER SEATTLE':'ROOF · 112 FLOORS ABOVE SEATTLE','EBENE 110 · TRESORGESCHOSS':'LEVEL 110 · VAULT LEVEL',
 // chips
 '16 vertikale Wege':'16 vertical routes','6 öffentlich':'6 public','4 Personal / Technik':'4 staff / technical','3 privat oder verborgen':'3 private or hidden','3 nur von außen':'3 from outside only','2 nur für Gegenstände':'2 for items only',
 '4 Sicherheit + Rollbot':'4 security + rollbot','6 Kameras':'6 cameras','Uniformen: Umkleide':'uniforms: locker room','Frachtaufzug ↑ 111 (110 kein Halt)':'freight elevator ↑ 111 (no stop at 110)','Kisten: eine Person passt':'crates: one person fits','Kunsttransporter wartet bis 05:00':'art transport waits until 05:00',
 '~80 Gäste':'~80 guests','7 Sicherheit + Kade':'7 security + Kade','9 Kameras':'9 cameras','6 Servicedrohnen':'6 service drones','Keycard: Eventbüro':'keycard: event office','Venn: Galerie ↔ Wintergarten':'Venn: gallery ↔ conservatory',
 '~15 VIP-Gäste':'~15 VIP guests','2 Sicherheit':'2 security','2 Kameras':'2 cameras','Suite: leer, Bewegungsmelder':'suite: empty, motion sensors','Skycab-Lobby prüft Buchungen':'skycab lobby checks bookings','Speiseaufzug ↔ Küche 111':'dumbwaiter ↔ kitchen 111',
 'Wind & Regen: Risky im Freien':'wind & rain: risky outdoors','Skycab-Pad mit Transponder':'skycab pad with transponder','Gondel geparkt (Ostfassade)':'gondola parked (east facade)','3 vertikale Wege nach unten':'3 vertical ways down','2 Glasdächer':'2 glass roofs',
 'kein Personal':'no staff','2 Aufklärer + 2 Wächter':'2 recon + 2 guardian drones','3 Lichtschranken · Druckplatten · RFID':'3 light barriers · pressure plates · RFID','Tür: Karte + Iris, 90 s Fenster':'door: card + iris, 90 s window','Manabarriere + Watcher':'mana barrier + watcher','5 Wege hinein':'5 ways in',
 // section rows & connectors
 '112 · Lounge, Suite,|Skycab-Lobby':'112 · lounge, suite,|skycab lobby','111 · Gala-Ebene':'111 · gala level','110 · Tresorgeschoss':'110 · vault level','EG · Lobby':'Ground floor · lobby','P2 · Tiefgarage':'P2 · parking garage',
 'Glasaufzug':'Glass elevator','VIP-Lobbyaufzug':'VIP lobby elevator','Frachtaufzug':'Freight elevator','Personaltreppe':'Staff stairs','Drohnenschacht':'Drone shaft','Wartungsschacht':'Maintenance shaft','Speiseaufzug':'Dumbwaiter','Freitreppe':'Grand staircase','Privattreppe':'Private stairs','Sammlerlift':'Collector lift','Privatlift':'Private lift','Steigleiter':'Access ladder','Skycab-Treppe':'Skycab stairs','Fassadengondel':'Facade gondola','Atrium & Glasdächer':'Atrium & glass roofs','Fassade Süd':'South facade',
 'Gäste':'Guests','Gäste per Auto':'Guests by car','Personal, Kisten':'Staff, crates','Personal, Notfall':'Staff, emergencies','nur Gegenstände':'items only','eine Person, eng':'one person, tight','Gegenstände, sehr schlanke Runner':'items, very slim runners','Venn, Wache, angemeldete Besucher':'Venn, guard, registered visitors','Kletterer':'Climbers','VIP per Luft':'VIPs by air','Rigger, Techniker':'Riggers, technicians','Abseilen':'Rappelling',
 'EG-Lobby':'Ground-floor lobby','P2 VIP-Vorfahrt':'P2 VIP drop-off','P2 Frachtvorraum':'P2 freight lobby','P2 Depot':'P2 depot','Dach Schachtkopf':'Roof shaft head','111 Küche':'111 kitchen','111 Salon':'111 salon','112 Suite':'112 suite','111 Vorraum Galerie':'111 gallery vestibule','111 Terrasse':'111 terrace','112 Skycab-Lobby':'112 skycab lobby','Dach BMU':'Roof BMU','Dach Wartungsflügel':'Roof maintenance vent','112 Sky-Terrasse':'112 sky terrace',
 '111 Foyer':'111 foyer','111 Kernflur':'111 core corridor','111 Küche · Dach Drohnenport':'111 kitchen · roof drone port','110 Löschzentrale':'110 suppression plant','112 Pantry':'112 pantry','112 Lounge':'112 lounge','111 Arbeitszimmer':'111 study','110 Schleuse':'110 airlock','Dach Nordkante':'Roof north edge','Dach Landeplattform':'Roof landing pad','110 Technische Schleuse · EG':'110 technical airlock · ground floor','112 Umgang · 111 Salon oder Wintergarten':'112 gallery walk · 111 salon or conservatory','111 Privatbalkon':'111 private balcony',
 'Einladung; Ankunft und Gesicht werden protokolliert':'Invitation; arrival and face are logged','Auftreten; geprüft wird erst oben':'Appearance; the real check waits upstairs','Badge + Scan; Halt auf 110 nur per Interface oder Rigger (Schachttür)':'Badge + scan; stop at 110 only via Interface or a rigger (shaft door)','Dachtür mit Alarmkontakt; 110 nur bei Feueralarm':'Roof door with alarm contact; 110 only during a fire alarm','40×40 cm; Rigger oder Hacker übernimmt eine Lieferdrohne':'40×40 cm; a rigger or hacker takes over a delivery drone','Revisionstür 111, Bodenluke 112; Bewegungssensor erst auf 110':'Inspection door 111, floor hatch 112; motion sensor only on 110','60×60 cm; für Personen Desperate':'60×60 cm; desperate for people','keine, aber jeder sieht, wer hinaufgeht':'None, but everyone sees who goes up','Suite-Reader, drei Bewegungsmelder; landet neben dem Privatlift':'Suite reader, three motion sensors; ends next to the private lift','Reader + Anmeldung; die Schleuse zählt Personen':'Reader + registration; the airlock counts people','Holzverkleidung; das Arbeitszimmer hat vier Türen':'Wood panelling; the study has four doors','8 m im Regen, Käfig oben verschlossen, Kamera zeigt woandershin':'8 m in the rain, cage locked at the top, camera points elsewhere','Buchung + Badge; Anflugtransponder hackbar':'Booking + badge; approach transponder hackable','protokolliert, von den Ostfenstern sichtbar; Dragon’s Deal: verriegelt sich danach':'Logged, visible from the east windows; Dragon’s Deal: locks itself afterwards','Atrium: alle sehen es. Wintergarten: leise, 5 m in Pflanzen':'Atrium: everyone sees it. Conservatory: quiet, 5 m into plants','3 m seitlich, 5 m tiefer; unten Bewegungsmelder':'3 m sideways, 5 m down; motion sensor below',
 'SL':'GM','GLT':'BMS','Gästeliste':'guest list','110: kein Halt':'110: no stop','110: Brandschutztür':'110: fire door','Ostfassade':'east facade','Seil':'rope',
 // rooms
 'Rampe':'Ramp','Fahrgasse':'Drive aisle','Stellplätze Bewohner':'Resident parking','Pförtner':'Gatekeeper','Umkleide':'Locker room','Sicherheits-|büro Garage':'Garage|security office','Technikraum':'Utility room','Lieferdrohnen-Depot':'Delivery drone depot','Fracht-|aufzug':'Freight|elevator','Frachtvorraum':'Freight lobby','Personal-|treppe':'Staff|stairs','GLT-|Verteiler':'Building|control node','Laderampe':'Loading dock','Kisten-|lager':'Crate|storage','Müll-|raum':'Waste|room','Anlieferung · Rangierfläche':'Deliveries · maneuvering area','VIP-Vorfahrt':'VIP drop-off','VIP-|Lobby-|aufzug':'VIP|lobby|elevator','Fahrer-|Lounge':'Drivers’|lounge',
 'Großer Salon':'Grand Salon','Gäste-WC':'Guest restrooms','Terrasse':'Terrace','Wintergarten':'Conservatory','Ausstellungsgalerie':'Exhibition gallery','Vorraum|Sammlerlift':'Collector lift|vestibule','Sammler-|lift':'Collector|lift','Arbeitszimmer':'Study','Privat-|lift':'Private|lift','Privatbalkon':'Private balcony','Bibliothek & Rauchsalon':'Library & smoking room','Foyer & Empfang':'Foyer & reception','Küche':'Kitchen','Personalflur':'Staff corridor','Kernflur':'Core corridor','Technik-|schacht':'Utility|shaft','Materiallager':'Storeroom','Personalgang':'Staff passage','Eventbüro':'Event office','Sicherheitsraum':'Security room',
 'VIP-Lounge & Umgang':'VIP lounge & gallery walk','Pantry & Lounge-Bar':'Pantry & lounge bar','Luftraum Atrium':'Atrium void','Luftraum':'Open void','Glasdach Wintergarten':'Conservatory glass roof','Private Suite':'Private suite','Bad':'Bath','Ankleide':'Dressing room','Privatsalon':'Private parlor','Sky-Terrasse':'Sky terrace','Skycab-Lobby':'Skycab lobby','Treppe|↑ Dach':'Stairs|↑ roof','Maschinenraum|Glasaufzug':'Machine room|glass elevator','Wartungs-|galerie':'Maintenance|gallery','Lüftung & Küchenabluft':'Ventilation & kitchen exhaust','Maschinen-|raum Fracht':'Freight|machine room','Technikschacht':'Utility shaft','Lager':'Storage','Technikflur':'Service corridor',
 'Flachdach über Lounge':'Flat roof above lounge','Flachdach über Suite':'Flat roof above suite','Glasdach Atrium':'Atrium glass roof','Dach-|ausstieg':'Roof|access','Schachtkopf':'Shaft head','Drohnen-|port':'Drone|port','Treppe|↓ 112':'Stairs|↓ 112','Gondel':'Gondola',
 'Zugangs-|schleuse':'Access|airlock','Sensorkorridor':'Sensor corridor','Authentifizierungspunkt':'Authentication point','Sammlung':'Collection','Drohnen-|knoten':'Drone|node','Technikflur Süd':'Service corridor south','Technikflur West':'Service corridor west','Technikflur Nord · Rohrleitungen':'Service corridor north · pipework','Technikflur Ost':'Service corridor east','Klimatechnik Vault':'Vault climate control','Technische Schleuse':'Technical airlock','Drohnenwerkstatt':'Drone workshop','Sicherheits-|server':'Security|server','Kuratoren-|vorbereitung':'Curators’|prep room','Sensorzentrale':'Sensor control','Lüftungszentrale 110':'Ventilation plant 110','Kernvorraum':'Core lobby','Löschzentrale':'Suppression plant','USV / Notstrom':'UPS / backup power','Kühlwassertanks':'Cooling water tanks','Kabelschacht':'Cable shaft',
 // room subtitles
 '↑ P1 · Straße':'↑ P1 · street','Spinde · Uniformen':'lockers · uniforms','Trafo · GLT-Knoten':'transformer · building control node','Racks · Ladeplätze':'racks · charging bays','Scan · Lieferscheine':'scan · delivery notes','↑ EG … Dach':'↑ ground floor … roof','Kisten · Rollwagen':'crates · carts','Valets · Limousinen · roter Teppich':'valets · limousines · red carpet','↑ EG':'↑ ground floor',
 'Bar · Bühne · Buffet · Freitreppe nach 112':'bar · stage · buffet · grand staircase to 112','offen bis zum Glasdach · Blick von 112 hinab':'open up to the glass roof · viewed from 112','Wind & Regen · 8 m unter der Dachkante':'wind & rain · 8 m below the roof edge','ruhig · Pflanzen · Glasdach':'quiet · plants · glass roof','AR-Provenienz · Dr. Venn':'AR provenance · Dr. Venn','privat · nicht Teil der Gala':'private · not part of the gala','leise · Kamin · Sammlergespräche':'quiet · fireplace · collectors’ talk','Gästeliste · Garderobe · Sicherheitsbogen':'guest list · cloakroom · security arch','↓ EG-Lobby':'↓ ground-floor lobby','Catering · Servicedrohnen-Dock':'catering · service drone dock','Anlieferung':'deliveries','Kunstdepot · Kisten':'art depot · crates','Personal-WC':'staff restroom','nur Eventpersonal':'event staff only','Kades Posten':'Kade’s post',
 'Balkon um das Atrium · Freitreppe ↓ 111':'balcony around the atrium · grand staircase ↓ 111','6 m hinab in den Salon · Glasdach 5 m darüber':'6 m down to the salon · glass roof 5 m above','Terrasse 111 liegt 4 m tiefer':'terrace 111 lies 4 m below','Luftraum · darunter Venns Rückzugsort':'void · Venn’s retreat below','Schlafraum · Veyrath · verschlossen · dunkel':'bedroom · Veyrath · locked · dark','Pool · Glasbalustrade · 112 Stockwerke Aussicht':'pool · glass balustrade · 112 floors of view','Ankunft per Luft · Empfang · Reader':'arrival by air · reception · reader','Lüftung · Technik · Bodenluke':'ventilation · utilities · floor hatch','↑ Dach ↓ 111':'↑ roof ↓ 111',
 'Glaspyramide · von unten sichtbar · 12 m bis zum Salonboden':'glass pyramid · visible from below · 12 m to the salon floor','flacher · dunkler · 5 m bis in die Pflanzen':'flatter · darker · 5 m down into the plants','Terrasse 111 · 8 m tiefer':'terrace 111 · 8 m below','Sky-Terrasse 112 · 4 m tiefer':'sky terrace 112 · 4 m below',
 'Karte + Iris · 90 s Fenster':'card + iris · 90 s window','kuratiert · nichts liegt zufällig':'curated · nothing lies here by chance','Gondel-Andockpunkt':'gondola docking point','Host-Knoten 110':'host node 110','kein Halt':'no stop','Treppe · Frachtschacht':'stairs · freight shaft','verriegelt':'locked',
 // openings
 'Personal':'Staff','Drohneneinflug 1×1 m':'Drone entry 1×1 m','Notausgang':'Emergency exit','Technik':'Utilities','Valets':'Valets','Ausgabe-|fenster':'Service|hatch','Service →':'Service →','Nur Personal':'Staff only','Service-|durchgang':'Service|passage','Privat':'Private','Holzverkleidung':'Wood panelling','Alarmkontakt':'Alarm contact','Wartungstür':'Maintenance door','Tresortür':'Vault door','Server':'Server','Schachttür (kein Halt)':'Shaft door (no stop)','Brandschutztür|verriegelt':'Fire door|locked',
 // item notes
 'Schranke · Kennzeichenscanner':'Barrier · plate scanner','Abgleich: Lieferplan & Bewohnerliste':'Checks: delivery schedule & resident list','Badges hängen an den Spinden':'Badges hang on the lockers','Monitore: nur Garage':'Monitors: garage only','plaudert mit dem Pförtner':'chats with the gatekeeper','Drohnen-|schacht':'Drone|shaft','keine Kamera':'no camera','Scan':'Scan','nur Außenscan':'external scan only','Tablet: Schichtliste,|fremder Name fällt auf':'Tablet: shift list,|an unknown name stands out','Fahrer schläft in der Kabine':'Driver sleeps in the cab','Rollbot (Patrouille, 4 Min.)':'Rollbot (patrol, 4 min)','Schranke VIP':'VIP barrier','Schlüsselboard:|Fluchtfahrzeuge':'Key board:|getaway vehicles',
 'Sicherheitsbogen':'Security arch','Freitreppe ↑ 112':'Grand staircase ↑ 112','Kade: Foyer ↔ Salon ↔ Galerie':'Kade: foyer ↔ salon ↔ gallery','Drohnen-Landeplatz':'Drone landing pad','Steigleiter ↑ Dach':'Access ladder ↑ roof','Venn zieht sich alle ~40 Min.|für 5 Min. hierher zurück':'Venn retreats here every ~40 min|for 5 minutes','Reader':'Reader','Privattreppe ↑ 112':'Private stairs ↑ 112','Papiernotizbuch':'Paper notebook','Speise-|aufzug':'Dumb-|waiter','Deckenhohlraum':'Ceiling void','Monitore Ebene 111':'Monitors level 111',
 'Freitreppe ↓ 111':'Grand staircase ↓ 111','Speise-|aufzug ↓':'Dumb-|waiter ↓','Pool':'Pool','Abseilpunkt: Privatbalkon 111|3 m östlich, 5 m tiefer':'Rappel point: private balcony 111|3 m east, 5 m down','Buchungen ↔ Gästeliste':'bookings ↔ guest list','Privattreppe ↓ 111':'Private stairs ↓ 111','Boden spürbar warm · keine Kameras|Türen und Möbel leicht zu groß':'floor noticeably warm · no cameras|doors and furniture slightly too large','Lüftungskanal':'Ventilation duct','Abluftlärm überdeckt Werkzeug':'exhaust noise covers tools','Lüftungsflügel: mechanisch, ohne Sensor, klemmt':'vent flap: mechanical, no sensor, sticks',
 'Skycab-Landeplattform':'Skycab landing pad','Anflug-|transponder':'Approach|transponder','Schacht ↓ 112 · 111 · 110':'Shaft ↓ 112 · 111 · 110','Drohnenschacht ↓ Küche · Garage':'Drone shaft ↓ kitchen · garage','Kühltürme':'Cooling towers','Steigleiter|↓ Terrasse 111':'Access ladder|↓ terrace 111','Wartungssteg':'Maintenance walkway','Scheiben tragen eine Person · Streben tragen mehr':'panes carry one person · struts carry more','Wartungsflügel Nordseite: Kontakt → Alert +1':'maintenance vent north side: contact → Alert +1','Antennen- & Blitzschutzmast':'Antenna & lightning mast','Landezone Ost|flach · keine Kamera|Windschatten des Masts':'Landing zone east|flat · no camera|lee of the mast','Attika 1,1 m · Böen: im Freien Position Risky':'parapet 1.1 m · gusts: risky position outdoors','Schiene der Fassadenbefahranlage':'Rail of the building maintenance unit','Wind aus SW':'Wind from SW',
 'Gewichtsplatte':'weight plate','Geräte-Scan':'device scan','ID-Terminal':'ID terminal','Werkzeug · Versteck':'tools · hiding place','lebendes Gewebe + duale Manabarriere':'living tissue + dual mana barrier','Kanal 60×60|Gitter + Kontakt|Gewebe zuckt':'duct 60×60|grille + contact|tissue twitches','Außentür nur mit Wartungsauftrag':'outer door only with maintenance order','zerlegter Wächter|Wartungstransponder':'disassembled guardian|maintenance transponder','Kabeldurchführung 30 cm':'cable pass-through 30 cm','astraler Watcher (Patrouille)':'astral watcher (patrol)','Schachtausstieg · Bewegungssensor':'shaft exit · motion sensor',
 // furniture labels
 'Rollwagen':'Cart','frei · Rückführung 05:00':'free · return at 05:00','Catering-Van':'Catering van','Vesperline Kunsttransporter (gepanzert)':'Vesperline art transport (armored)','toter Winkel':'blind spot','Limousine':'Limousine','Valet':'Valet','Empfang P2':'Reception P2','Presse':'Compactor','Garderobe':'Cloakroom','Empfang':'Reception','Bühne|& DJ':'Stage|& DJ','Buffet':'Buffet','Raucher-|nische':'Smokers’|nook','Gemälde':'Painting','Skulptur':'Sculpture','Vitrine':'Display case','Installation':'Installation','Schreibtisch':'Desk','Wagen':'Cart','Tisch':'Table','Bett':'Bed','Sofa':'Sofa','Lüftungsgeräte':'Air handlers','Notstrom / USV':'Backup power / UPS','BMU-|Steuerung':'BMU|controls','Cybertech':'Cybertech','mag. Antiquität':'magical antique','Waffen':'Weapons','Schatulle':'Casket','Bücher · Archive':'Books · archives','Koffer':'Case','Packtisch|Werkzeug':'Packing table|tools','Klimagerät':'Air handling unit','Sensorsteuerung':'Sensor controller',
 // legend
 'Räume':'Rooms','Öffentlich / Gäste':'Public / guests','Service / Personal':'Service / staff','Gesichert':'Secured','Privat (Veyrath)':'Private (Veyrath)','Außen / Terrasse':'Outdoors / terrace','Kern (Aufzug, Treppe, Schacht)':'Core (elevator, stairs, shaft)','Luftraum / offen nach unten':'Void / open below','Vault (lebendes Gewebe)':'Vault (living tissue)','Öffnungen':'Openings','Tür':'Door','Tür mit Reader / Badge':'Door with reader / badge','Mechanisches Schloss':'Mechanical lock','Brandschutztür (öffnet bei Feueralarm)':'Fire door (opens on fire alarm)','Glastür / Fenster':'Glass door / window','Rolltor / Schranke':'Roll gate / barrier','Schleusentür':'Airlock door','Aufzugstür':'Elevator door','Verborgen / nur SL bekannt':'Hidden / GM only','Revisionsluke':'Inspection hatch','Treppe (Pfeil = aufwärts)':'Stairs (arrow = up)','Aufzug':'Elevator','Sicherheit & Personen':'Security & people','Kamera mit Blickfeld':'Camera with field of view','Lichtschranke':'Light barrier','Druckplatte':'Pressure plate','Bewegungsmelder':'Motion sensor','Sicherheit (S)':'Security (S)','Dorian Kade (K)':'Dorian Kade (K)','Dr. Amara Venn (V)':'Dr. Amara Venn (V)','Aufklärungsdrohne':'Recon drone','Wächterdrohne':'Guardian drone','Toter Winkel':'Blind spot','Astraler Watcher (Patrouille)':'Astral watcher (patrol)','Manabarriere / magische Aura':'Mana barrier / magical aura','Koffer (Ziel)':'Case (target)','Keycard-Kassette':'Keycard box','Wege (Overlay)':'Routes (overlay)','Als Gast / öffentlich':'As a guest / public','Als Personal':'As staff','Technik / verdeckt':'Technical / covert','Außen / Fassade / Luft':'Outside / facade / air','Privat / verborgen':'Private / hidden','gestrichelt = nur Gegenstände, Abseilen oder Sonderfall':'dashed = items only, rappelling or special case',
 // Legend: person tokens
 'Personal ':'Staff','Gäste ':'Guests',
},
ui:{
 subtitle:'Plans for the parking garage, penthouse, roof and vault level · Seattle 2080',tabs:{schnitt:'Vertical routes',garage:'Parking garage',111:'Gala level',112:'Lounge & suite',dach:'Landing pad',110:'Vault level'},
 short:{schnitt:'Section',dach:'Roof'},gmOn:'GM view',gmOff:'Player view',routes:'Show routes',print:'Print view',back:'Back to the plans',
 spots:'Locations on the plan',routesH:'From A to B',sits:'Play situations',cons:'Vertical connections',
 routesHint:'The letters mark the starting point of each route on the plan. “Show routes” toggles the overlay.',
 consHint:'Circles = stops, red cross = level passed but not reached. Dashed = items only or rope.',
 th:['No.','Connection','From → To','Who','Price / risk'],gmTag:'GM',gmSuffix:' · GM',tbSuffix:'1 unit = 1 m · walls schematic',sectionTb:'MERIDIAN SPIRE · SECTION · vertical connections (schematic, not to scale)',
 printGm:'GM plans',printPlayer:'Player plans',printHint:'One level per A4 landscape page. GM plans add a notes page per level; player plans show only what the crew can know. Printing works from the file in the repo or the PDFs, not from the claude.ai view.',
 printBtn:'Print',orte:'Locations',wege:'Routes',legende:'Legend',notesTitle:'GM notes',playerBadge:'PLAYER PLAN',gmBadge:'GM PLAN',pageOf:'Sheet',
 fine:'Fan material for the private gaming table. <i>Runners in the Shadows</i> is a game by Mark Cleveland Massengale; <i>Shadowrun</i> is a trademark of The Topps Company / Catalyst Game Labs. The Meridian Spire and everyone in it are original creations for the Feuerprobe one-shot.',
},
aria:{schnitt:'Schematic section through the upper levels of the Meridian Spire: 16 vertical connections between parking garage, ground floor, levels 110, 111, 112 and the roof.',garage:'Floor plan parking garage P2: ramp in the north-east, drive aisle across the middle, delivery drone depot and freight elevator in the north-west, loading dock with three gates in the south-west, maneuvering area in the middle, VIP drop-off with lobby elevator in the south-east.',111:'Floor plan level 111: foyer in the south-west, salon with atrium in the middle, gallery in the east, conservatory in the north-east, terrace in the north, service area in the west, study in the south-east.',112:'Floor plan level 112: VIP lounge as a gallery walk around the atrium void, private suite in the east, sky terrace with pool in the south, skycab lobby in the south-west, maintenance gallery and utilities in the west.',dach:'Roof plan: skycab landing pad in the south-west, plant rooms in the west, glass pyramid above the atrium in the middle, glass roof above the conservatory in the north-east, antenna mast and building maintenance unit in the east, voids above terrace and sky terrace.',110:'Floor plan level 110: access airlock with both lifts in the south-east, sensor corridor west and north to the authentication point, vault in the middle, service ring around the vault, technical airlock for the gondola at the east facade, core lobby with freight shaft and stairs in the west.'},
chips:{},spots:{},sits:{},routes:{}};
