/* English long texts for levels 111 and 112, keyed by level id, spot number / route letter / situation index. */
PLAN_EN.spots['111']={
1:{t:'Glass elevator, foyer & reception',p:'The glass elevator rides up the outside of the facade and opens straight into the foyer. Two security staff check the guest list, the cloakroom takes coats and bags, an unobtrusive arch stands at the transition to the salon.',g:'The arch detects weapons and heavy cyberware but only reports silently to Kade: conspicuous guests are not stopped but watched (Alert +1, one guard stays in view). The cloakroom is the perfect stash for a flashback (“the bag has been hanging here since 9 pm”). The elevator log stores arrival time and face.'},
2:{t:'Grand Salon & atrium',p:'The social heart: ~50 guests, bar, stage, buffet, service drones with drinks. Above the atrium the room opens up to the glass roof; the grand staircase leads to the VIP lounge on 112.',g:'The crowd is cover, but two cameras see almost everything. Service drones can be hijacked (distraction: a tray drops; transport: a keycard or commlink travels across the room). Anyone standing on the glass roof throws a silhouette over the party during lightning. Two security staff; Kade makes his rounds foyer → salon → gallery.'},
3:{t:'Terrace',p:'Open to the sky, wind and rain. To the west the landing pad of the service drones, to the east a covered smokers’ nook. Doors to the kitchen, the salon and the conservatory.',g:'Only one camera, pointed at the landing pad; the smokers’ nook is unwatched. The service door to the kitchen is often left ajar (staff smoke here). Access ladder to the roof: cage locked at the top, climbable around the outside (Prowl, risky). The terrace is the bypass around the party: kitchen → terrace → conservatory → gallery.'},
4:{t:'Conservatory',p:'A quiet retreat with living plants and its own glass roof. Dr. Venn escapes the small talk here.',g:'No camera (“guest privacy”). Venn is alone here for about 5 minutes every ~40 minutes: the best spot for a high-resolution iris capture or a serious conversation about art. The glass roof above is the quieter roof entry (see roof ⑥).'},
5:{t:'Exhibition gallery & collector lift',p:'Eight pieces on plinths, AR overlays with provenance and price. Dr. Venn gladly explains details to anyone seriously interested. At the back the vestibule to the collector lift: reader, one guard.',g:'Every ~40 minutes a piece is taken back down to 110: Venn, one guard and a transport cart ride the collector lift (a lift to hitch, a crate, a logistics disguise). For that, Kade’s clearance fetches the keycard from the event office: it is then out of the box for 10 minutes. The reader demands a security badge or Venn’s registration. Two cameras.'},
6:{t:'Library & smoking room',p:'Leather, fireplace, few guests, hushed conversation. This is where the serious collectors sit.',g:'No camera. The door to the study has a mechanical lock (not hackable, but lockpicks or force work). Guests here know things: who Venn is, that Kade “with the chrome arms” sees everything, that the gala ends at 3 am.'},
7:{t:'Study (private)',p:'Locked, sign “Private”. Not part of the event.',g:'Four entrances: gallery door (reader + alarm contact), library door (mechanical), private stairs from the suite on 112, private balcony (facade, rappel from the sky terrace 112). Motion sensor + camera. Behind the flush wood panelling lies the private lift to 110 (finger-wide gap, warm draft). On the desk a paper notebook in the same handwriting as Mr. Johnson’s notes.'},
8:{t:'Kitchen & core corridor',p:'Catering in full swing, service drones dock. The freight elevator and deliveries arrive in the core corridor; a guard scans delivery notes and crates.',g:'The scan checks badge and load list but opens no crates (metal and radio stand out; “stage equipment” explains a lot). Drone shaft 40×40 cm: garage ↔ kitchen ↔ roof, have gear delivered in portions. Dumbwaiter 60×60 cm to the pantry on 112. The head chef remembers unfamiliar faces, not uniforms.'},
9:{t:'Storeroom / art depot',p:'Vesperline transport crates, tools, an art transport cart.',g:'An empty crate holds one person. Blind spot behind the crates. Behind a shelf the inspection door to the utility shaft: inside, the maintenance shaft with a ladder down to 110 (suppression plant) and up to the roof. Motion sensor only on 110.'},
10:{t:'Event office',p:'Small office, door “Event staff only”, a service hatch to the staff corridor.',g:'The keycard lies in the black box; removal only with Kade’s clearance, everything is logged. The event manager drops by every ~15 minutes. Camera inside. The suspended ceiling connects locker room, staff passage, storeroom and office (ceiling void, barely carries one person). At the hatch, anyone who plausibly cites Kade’s clearance gets the card handed over the counter.'},
11:{t:'Security room',p:'Kade’s post: monitor wall, radio, doors to the foyer and the staff corridor.',g:'Kade is away 60 % of the time. Monitors show all cameras of this level, not those of 110 (separate system). Anyone standing here can lower Alert: swap footage, mark a sensor as defective. The window to the foyer is mirrored glass.'},
12:{t:'Guest restrooms',p:'Vestibule with mirrors, stalls behind. In the vestibule a door “Staff only”.',g:'The staff door leads into the staff corridor, simple cylinder lock. Classic role change: in as a guest, out as staff (uniform from the locker room opposite). No camera in the restrooms.'},
};
PLAN_EN.routes['111']={
A:{t:'As a guest to the collector lift',d:'Glass elevator → foyer → arch → salon → gallery → vestibule. Needs an invitation; at the vestibule a badge or Venn’s registration.'},
B:{t:'As staff to the keycard',d:'Freight elevator → core corridor (scan) → staff corridor → staff passage → event office (badge reader). Uniform + a reason to be in the office.'},
C:{t:'Library → study → private lift',d:'Mechanical lock, motion sensor, wood panelling. Quiet, no reader log, but the alarm contact on the gallery door stays untouched.'},
D:{t:'Storeroom → maintenance shaft → 110',d:'Inspection door behind the shelf, narrow shaft with a ladder. No staff, but a motion sensor at the exit on 110.'},
E:{t:'Around the outside: kitchen → terrace → conservatory → gallery',d:'Bypasses salon and arch. Wind, rain, one camera at the landing pad. Ends right next to Venn.'},
F:{t:'Ceiling void → event office',d:'Crawl from the locker room or storeroom over the partition wall. Barely carries one person; the office camera points downward.'},
};
PLAN_EN.sits['111']=[
 '<b>Return transport.</b> Every ~40 minutes a piece goes back to 110: Venn, a guard, a transport cart. For that the keycard leaves its box for 10 minutes and travels core corridor → gallery → vestibule. Both factors are briefly in the same place.',
 '<b>Silent check.</b> The arch only reports to Kade. Anyone conspicuous gets no scene, just a shadow. Attentive runners notice: the same guard is always within sight.',
 '<b>Venn alone.</b> In the conservatory without a camera, five minutes. Iris capture, honest conversation, invitation to a private viewing: this is where it is decided whether the biometric factor is solved socially or technically.',
 '<b>Four doors into the study.</b> Reader (hacker), mechanical (snake/punk), stairs from above (prowl), balcony (rigger/adept). Every crew finds its own.',
 '<b>Role change in the restroom.</b> In as a guest, out through the staff door. The locker room with uniforms is right opposite.',
 '<b>Service hatch.</b> A runner in security uniform demands the card “on Kade’s orders for the return transport”. Sway or Command, risky. On a 4/5 the event manager calls Kade to confirm.',
];
PLAN_EN.spots['112']={
1:{t:'VIP lounge & gallery walk',p:'A balcony runs around the atrium. Few, very well-connected guests, lounge furniture, the grand staircase down into the salon. From the railing you see the whole party.',g:'Fewer guests means more attention per person: anyone who does not belong stands out within minutes. One security officer, two cameras. The railing is overwatch for a trigger and the fastest way down (rope into the atrium, 6 m). Service drones fly through the void.'},
2:{t:'Pantry & dumbwaiter',p:'A small bar kitchen for the lounge; supplies come up by dumbwaiter from the kitchen on 111.',g:'Dumbwaiter 60×60 cm: items, a keycard handover between two runners on different levels, at a pinch a very slim runner (desperate). Two service staff who rarely look up.'},
3:{t:'Sky terrace & pool',p:'Outdoor terrace with heated pool, glass balustrade, wind. Doors to the lounge, the skycab lobby and the suite.',g:'No camera except the one at the lobby door. The balustrade is a rappel point to the private balcony 111 (3 m east, 5 m down) and the escape route for anything that flies. The facade gondola passes along the east edge. The suite door is locked, but glass.'},
4:{t:'Skycab lobby',p:'Arrival for guests who come by skycab: reception, reader, stairs to the landing pad on the roof.',g:'One security officer checks skycab bookings against the guest list; anyone with a booking entered counts as expected. The reader to the lounge needs the guest badge. Escape route number one at low Alert: order a skycab, up the stairs, gone. Camera above the door.'},
5:{t:'Private suite',p:'Locked, dark, not part of the gala.',g:'Empty. Motion sensors in three corners, no cameras (Veyrath tolerates none in his rooms). The private stairs in the parlor lead directly into the study on 111: the way to the private lift that bypasses gallery and library entirely. Hints about the owner: warm floor, oversized doors and furniture, tailored suits without labels in the dressing room.'},
6:{t:'Maintenance gallery & utilities',p:'Ventilation plant, ducts, staff stairs, a storage room with furniture. Loud.',g:'Floor hatch into the utility shaft: the maintenance shaft leads down to the storeroom on 111 and on to the suppression plant on 110, up to the roof. The staff stairs continue to the roof (door with alarm contact). The exhaust noise covers tool sounds.'},
7:{t:'Service corridor',p:'Staff connection between pantry and skycab lobby.',g:'No camera. Service staff and VIP reception cross paths here: the best place to swap a uniform for a suit or the other way round.'},
8:{t:'Conservatory glass roof (void)',p:'From here you look down through the glass into the conservatory.',g:'From the roof: vent flap for ventilation, mechanical, no sensor, sticks (Prowl or Engineer, controlled when calm). Below, Venn’s camera-free retreat. 5 m of rappelling into plants.'},
9:{t:'Atrium void',p:'A view 6 m down onto the party, 5 m up to the glass roof.',g:'Fall hazard for consequences. A rope from the railing is the fastest way down and up (glass roof maintenance vent). Anyone hanging here is seen.'},
};
PLAN_EN.routes['112']={
A:{t:'By skycab into the party',d:'Landing pad → stairs → skycab lobby (booking + badge) → lounge → grand staircase → salon. In reverse the most elegant escape.'},
B:{t:'Lounge → suite → private stairs → study',d:'Reader on the suite door, three motion sensors, nothing else. Ends right next to the private lift, without gallery and library.'},
C:{t:'Pantry → service corridor → maintenance gallery → floor hatch',d:'Camera-free all the way to the shaft. Down to the storeroom on 111 or all the way to 110.'},
D:{t:'Sky terrace → rappel to the private balcony 111',d:'Wind, rain, glass. Prowl, risky. Below, the motion sensor in the study is waiting.'},
E:{t:'Staff stairs → service corridor → lounge',d:'The service staff’s route: coming from 111 or the roof, into the lounge without a reader.'},
};
PLAN_EN.sits['112']=[
 '<b>Who belongs here?</b> In the VIP lounge everyone knows everyone. An unfamiliar face is addressed, not reported: “And you are here with whom?” A face shines, a muscle sweats.',
 '<b>Skycab booking.</b> A hacker enters a booking into the arrival system before the run. Then the lobby guard expects guests, not intruders. Without a booking: a polite query, Alert +1.',
 '<b>The suite smells of dragon.</b> Whoever gets in finds nothing useful but many hints: warm floor, huge bed, tailored suits. A mage senses an old, calm presence. No alarm, but a hunch.',
 '<b>From top to bottom.</b> Four ways from 112 to 111: grand staircase (public), private stairs (hidden), staff stairs (staff), rope into the atrium (spectacular).',
 '<b>Pool party.</b> A consequence on the sky terrace: someone falls into the pool, everyone looks. Two minutes in which nobody watches the lounge.',
];
