/* English long texts for the roof and level 110. */
PLAN_EN.spots['dach']={
1:{t:'Skycab landing pad',p:'Lit platform with a shelter and stairs down to the skycab lobby on 112. At night autonomous skycabs land here with VIP guests.',g:'The approach transponder grants autonomous skycabs landing clearance: hacked, every cab lands as a “registered arrival”; without clearance it circles for 90 seconds and calls in (Alert +1). Camera at the shelter. Landing zone B for parachutes: flat, but brightly lit.'},
2:{t:'Roof access, staff stairs',p:'The only regular way onto the roof: steel door, reader.',g:'Alarm contact: opening without a badge reports silently (Alert +1). Camera and motion sensor in front. The stairs lead down to P2: 112 maintenance gallery, 111 core corridor, past 110 (locked fire door), ground-floor lobby, garage.'},
3:{t:'Utility shaft head',p:'An inconspicuous hatch between the plant rooms.',g:'Below it the maintenance shaft (80×80 cm) with a ladder: exits on 112 (floor hatch, maintenance gallery), 111 (inspection door, storeroom) and 110 (suppression plant). No sensor until 110. The most direct way from the roof to the vault without touching the party.'},
4:{t:'Drone port',p:'Delivery drones land here and disappear into a shaft into the building.',g:'Drone shaft 40×40 cm down to the kitchen on 111 and on to the garage. A rigger sends gear down or up in portions. The constant drone traffic covers small flying devices of your own. No camera.'},
5:{t:'Atrium glass roof',p:'A lit glass pyramid above the salon. From below every silhouette on the glass is visible.',g:'Struts carry, panes carry one person. Maintenance vent on the north side with a contact. Anyone standing here is seen from below during lightning (consequence: a guest points up). Rappelling: 12 m to the salon floor. A fall through the glass is a possible consequence, never the automatic result.'},
6:{t:'Conservatory glass roof',p:'A flatter, dark glass roof above the conservatory.',g:'Vent flap mechanical, no sensor, sticks (Prowl/Engineer). Below, Venn’s retreat without a camera, 5 m of rappelling into soft plants. The quiet roof entry.'},
7:{t:'Building maintenance unit (gondola)',p:'Maintenance crane with a cleaning gondola, parked at the east edge. Runs on a rail along the facade.',g:'Controls manual at the box or via Interface. The gondola runs along the east facade down to the technical airlock on 110 (docking point) and on to the ground floor. Rides are logged; deviation from the maintenance schedule → silent check. Dragon’s Deal: “It takes you exactly to the target and then locks itself to the outside.”'},
8:{t:'Access ladder',p:'Maintenance ladder at the north edge, down to the terrace on 111.',g:'8 m, cage locked at the top, climbable around the outside. The terrace camera only sees the drone landing pad, not the ladder. Whoever arrives here stands right next to the kitchen service door left ajar.'},
9:{t:'Landing zone east',p:'',g:'Flat roof above the suite, no camera, lee of the mast. The best drop point for parachute or glider. Caution: parapet only 1.1 m, gusts. From here on foot around the glass pyramid to the roof access.'},
10:{t:'Plant rooms',p:'Cooling towers, air handlers, backup power. Loud, warm, steaming.',g:'Cover and noise. Sabotaging backup power/UPS triggers emergency lighting and the lockdown protocol (Alert +2): a bad idea as an entry, a good distraction for the escape.'},
};
PLAN_EN.routes['dach']={
A:{t:'Skycab pad → stairs → lobby 112',d:'The official way. Welcomed warmly with a booking, politely questioned without one.'},
B:{t:'Roof access → staff stairs',d:'Reader + alarm contact + camera. Leads to 112, 111 and beyond. The route security expects.'},
C:{t:'Shaft head → maintenance shaft',d:'Tight, dark, no sensor until 110. Exits on 112, 111, 110. The way around the party.'},
D:{t:'Conservatory glass roof → conservatory 111',d:'Flap sticks, no sensor, 5 m of rope into plants. Venn below without a camera.'},
E:{t:'Gondola → technical airlock 110',d:'Down the outside of the facade. Logged, visible to guests at the east windows, but it bypasses the whole penthouse.'},
F:{t:'Access ladder → terrace 111',d:'8 m of ladder in the rain. Lands next to the kitchen door.'},
G:{t:'Landing zone east → around the pyramid → roof access',d:'On foot across the roof: lee first, then open. The camera at the roof access sees you coming.'},
H:{t:'Atrium glass roof → salon',d:'Spectacular: maintenance vent, 12 m of rope into the middle of the party. Everyone sees it. Only at full Alert or as a grand entrance.'},
};
PLAN_EN.sits['dach']=[
 '<b>Approach without clearance.</b> The skycab circles, building security asks questions. With hacked clearance the lobby guard expects “guests” and holds the door.',
 '<b>Silhouettes.</b> Lightning over Seattle. Anyone standing on the atrium glass is seen from below: “a guest points up” is the consequence, not an alarm right away.',
 '<b>Gust.</b> On a 4/5 outdoors: gear slides toward the parapet, the glider snags on the mast, the gondola sways. Harm or lost equipment instead of Alert.',
 '<b>The gondola runs only once.</b> Dragon’s Deal: exactly to the target, then it locks itself to the outside of the building. The crew needs something else for the escape.',
 '<b>Three ways down.</b> Stairs (alarm contact, camera), maintenance shaft (tight, sensor only on 110), ladder (terrace, kitchen door). The choice decides where the crew arrives and who sees them.',
];
PLAN_EN.spots['110']={
1:{t:'Access airlock',p:'Both lifts end in the same matte-black airlock. Sensors register movement, weight and devices. A terminal asks for identity.',g:'The weight plate counts people and compares with the registration. The device scan flags radio and metal. A camera with face matching recognizes Venn and greets her by name. Deviation → silent alarm, the airlock door locks behind the crew (a consequence, not a dead end: the door opens from inside with Engineer or force). In the west wall a maintenance door with reader to the east service corridor: for the trapped the way out into the service ring, for a gondola crew the way into the airlock without using a lift. Whoever opens it without a maintenance badge counts as unregistered for the sensors.'},
2:{t:'Sensor corridor',p:'A long, surprisingly empty corridor. Museum lighting, then a turn to the north.',g:'Three light barriers (x positions marked), pressure plates before the turn, RFID arch in the turn, three cameras. During an “authorized viewing” everything stays armed, but the judgement is kinder: position controlled instead of risky. Foam nozzles in the ceiling flood the corridor on alarm (vision and movement impaired, drone sensors too). A recon drone patrols here.'},
3:{t:'Authentication point & vault door',p:'A console with card reader and iris scanner in front of a massive door.',g:'Order does not matter, 90-second window. With only one factor: “BIOMETRIC FACTOR: CONFIRMED · PHYSICAL FACTOR: PENDING”. Every attempt is logged. Without factors: 40 cm of composite, tissue and barrier, so loud, long or magically demanding, never impossible. The curators’ prep room next door is a hiding place with tools.'},
4:{t:'Drone node',p:'A side niche with charging bays. It hums.',g:'Two recon drones, two guardians. Three states: routine (patrol), viewing (escort, count), irregularity (block, separate, only then weapons). The maintenance ports are an Interface point. The maintenance door at the back leads to the south service corridor: the back entrance into the corridor, right through the nest.'},
5:{t:'Collection (vault)',p:'',g:'Walls of living tissue carrying a dual mana barrier (reacts to drilling and shock, heals small wounds, densifies on alarm). The case lies on a low plinth at the very back: the way there passes the jewel casket right next to the door, the cybertech and the magical antique. Packing table with tools and packaging. Ventilation grille inside on the east wall.'},
6:{t:'Technical airlock (gondola)',p:'Visible from outside as the facade gondola’s docking point.',g:'The outer door opens only with a maintenance order in the system (Interface or forged order) or with force (loud). Camera inside. From here: east service corridor → maintenance door into the corridor (alarm contact), maintenance door into the access airlock (reader, sensors count along) or climate control → ventilation duct.'},
7:{t:'Climate control & ventilation duct',p:'',g:'The duct (60×60 cm) leads through the east wall into the collection. Grille with contact and vibration sensor; the tissue grows around the duct and twitches when cut (Alert +1, visible trace). The barrier closes the duct astrally. A reported climate fault at the “sensitive object” is the perfect pretext to lure Venn to the airlock.'},
8:{t:'Security server / host node',p:'',g:'Physical access to doors, sensors and drone logic of this level (not 111, separate system). Cable pass-through 30 cm to the authentication room: a micro drone or a cable fits. Interface here is controlled, but every login is logged: no Alert now, Heat later.'},
9:{t:'Sensor control',p:'',g:'Local controller of the corridor sensors. Anyone standing here can mark sensors as “under maintenance” (Engineer or Interface): corridor blind for five minutes. Door with reader from the east service corridor.'},
10:{t:'Core lobby, freight shaft & staff stairs',p:'The staff stairs pass this level; the fire door is locked.',g:'The freight elevator does not stop here, but the shaft door exists: stop the cab on 110 via Interface or a rigger, open the door manually. The fire door unlocks during a fire alarm (Alert +2, guests are evacuated, but chaos is cover). Utility shaft: maintenance shaft exit into the suppression plant, motion sensor there.'},
11:{t:'Suppression plant',p:'',g:'Stock of the security foam for the corridor. Whoever controls the plant releases the foam or prevents it. Exit of the maintenance shaft with a motion sensor.'},
12:{t:'Drone workshop',p:'',g:'Spare parts, a disassembled guardian, maintenance transponders: drones ignore whatever broadcasts as a “maintenance device” (spoofing target recognition, Engineer or Interface). Tools for everything that was missing upstairs.'},
13:{t:'Astral watcher & mana barrier',p:'',g:'The watcher patrols astrally around the vault (violet loop), reports unusual astral activity (Alert +1) and does not fight. At the doorway the barrier is opened in a controlled way: a mage can study the mechanism with Assense and gain an advantage for a route of their own.'},
};
PLAN_EN.routes['110']={
A:{t:'Regular: lift → airlock → corridor → vault door',d:'The intended way with both factors. With Venn and a registration controlled, as an intruder risky to desperate.'},
B:{t:'Gondola → technical airlock → east service corridor → maintenance door',d:'Bypasses the lifts. At the south end two doors: into the corridor behind the light barriers (alarm contact) or into the access airlock (reader, where the sensors count the crew).'},
C:{t:'Maintenance shaft → suppression plant → service ring → drone node (rear)',d:'Long, dark, no cameras in the ring. Ends in the middle of the drone nest; on routine the drones sleep at their docks.'},
D:{t:'Climate control → ventilation duct → collection',d:'60×60 cm, grille with contact, the tissue twitches. Bypasses the vault door completely, but not the barrier (closed astrally).'},
E:{t:'Fire alarm: staff stairs → core lobby → service ring',d:'The fire door only unlocks on alarm. Loud, but the chaos upstairs is cover.'},
};
PLAN_EN.sits['110']=[
 '<b>Three states.</b> The drones react to context: routine, viewing or irregularity. A social success upstairs changes how this level greets the crew, but does not remove the drones.',
 '<b>The way to the case passes everything.</b> Casket next to the door, cybertech on the left, antique with an aura in the middle. Describe it all before the case is even visible.',
 '<b>Factor missing.</b> Venn scans, the display says “PHYSICAL FACTOR: PENDING”. 90 seconds. Where is the card right now, and who is standing next to Venn?',
 '<b>Back entrance through the nest.</b> Whoever comes via the service ring enters the corridor through the drone node. Controlled if nobody touches anything; desperate if the guardians are already awake.',
 '<b>Foam.</b> A consequence in the corridor: security foam from the ceiling. Vision and movement impaired, for everyone. Whoever controls the suppression plant decides when.',
 '<b>The watcher sees you.</b> Astral activity → report (Alert +1), no attack. A mage can distract it, fool it or simply stay still.',
 '<b>The door slams shut.</b> Dragon’s Deal: “You reach the case without resistance. In return the vault door closes behind you.” Now the ventilation duct, the cable pass-through and the packing table with tools matter.',
];
