const LDACH={
id:'dach',name:'Dach',short:'Dach',sub:'Landeplattform, Glasdächer, Gondel & drei Wege nach unten',tb:'DACH · 112 STOCKWERKE ÜBER SEATTLE',view:[1040,790],plate:[40,40,920,680],scale:20,
aria:'Dachplan: Skycab-Landeplattform im Südwesten, Technikaufbauten im Westen, Glaspyramide über dem Atrium in der Mitte, Glasdach über dem Wintergarten im Nordosten, Antennenmast und Fassadenbefahranlage im Osten, Lufträume über Terrasse und Sky-Terrasse.',
chips:['2 Kameras','Wind & Regen: Risky im Freien','Skycab-Pad mit Transponder','Gondel geparkt (Ostfassade)','3 vertikale Wege nach unten','2 Glasdächer'],
rooms:[
 {x:40,y:40,w:260,h:680,t:'roof'},
 {x:300,y:150,w:400,h:420,t:'roof',label:'Flachdach über Lounge',small:true,lx:500,ly:182},
 {x:700,y:230,w:260,h:490,t:'roof',label:'Flachdach über Suite',small:true,lx:830,ly:680},
 {x:400,y:250,w:220,h:220,t:'glass',label:'Glasdach Atrium',sub:'Glaspyramide · von unten sichtbar · 12 m bis zum Salonboden',lx:510,ly:360},
 {x:700,y:40,w:260,h:190,t:'glass',label:'Glasdach Wintergarten',sub:'flacher · dunkler · 5 m bis in die Pflanzen',lx:830,ly:130},
 {x:260,y:40,w:440,h:110,t:'void',label:'Luftraum',sub:'Terrasse 111 · 8 m tiefer',lx:480,ly:95},
 {x:300,y:570,w:400,h:150,t:'void',label:'Luftraum',sub:'Sky-Terrasse 112 · 4 m tiefer',lx:500,ly:645},
 {x:40,y:270,w:70,h:90,t:'core',label:'Dach-|ausstieg',small:true,sub:'Personaltreppe',lx:75,ly:305},
 {x:40,y:360,w:70,h:40,t:'core',label:'Schachtkopf',small:true,lx:75,ly:372},
 {x:40,y:150,w:70,h:60,t:'core',label:'Drohnen-|port',small:true,lx:92,ly:175},
 {x:250,y:660,w:50,h:60,t:'core',label:'Treppe|↓ 112',small:true},
 {x:962,y:590,w:34,h:60,t:'outdoor',thin:true,label:'Gondel',small:true,lx:979,ly:580},
],
ops:[
 {x:106,y:300,w:8,h:40,k:'reader',lbl:'Alarmkontakt',lx:175,ly:284},
 {x:246,y:675,w:8,h:30,k:'door',flip:true},
],
items:[
 // Skycab pad
 {k:'pad',x:160,y:600,r:88},{k:'text',x:160,y:706,text:'Skycab-Landeplattform'},
 {k:'rect',x:50,y:500,w:22,h:14,cls:'furn-dark'},{k:'text',x:110,y:530,text:'Anflug-|transponder',cls:'gmtxt',gm:true},
 {k:'stair',x:250,y:660,w:50,h:60,dir:'v'},
 {k:'cam',x:245,y:664,a:200,len:110,spread:22},
 // Stair head, shaft head, drone port
 {k:'stair',x:40,y:270,w:70,h:90,dir:'v'},{k:'cam',x:120,y:262,a:70,len:80,spread:22},{k:'motion',x:114,y:320,a:0,r:40,spread:40,gm:true},
 {k:'shaft',x:40,y:360,w:70,h:40},{k:'hatch',x:96,y:390,gm:true},{k:'text',x:100,y:414,text:'Schacht ↓ 112 · 111 · 110',cls:'gmtxt',gm:true},
 {k:'shaft',x:40,y:165,w:35,h:35},{k:'staff',x:92,y:195,t:'d'},{k:'text',x:150,y:228,text:'Drohnenschacht ↓ Küche · Garage',cls:'note'},
 // Technik
 {k:'circle',x:160,y:185,r:28,cls:'glyph-fill'},{k:'circle',x:215,y:232,r:22,cls:'glyph-fill'},{k:'text',x:185,y:272,text:'Kühltürme'},
 {k:'rack',x:150,y:330,w:90,h:40,lbl:'Lüftungsgeräte'},{k:'rack',x:150,y:420,w:90,h:40,lbl:'Notstrom / USV'},
 {k:'ladder',x:268,y:152,dir:'h',len:22},{k:'text',x:300,y:190,text:'Steigleiter|↓ Terrasse 111'},
 // Glasdach Atrium
 {k:'rail',pts:[[384,234],[636,234],[636,486],[384,486],[384,234]]},{k:'text',x:510,y:228,text:'Wartungssteg'},
 {k:'line',x1:400,y1:250,x2:620,y2:470,cls:'glassline'},{k:'line',x1:620,y1:250,x2:400,y2:470,cls:'glassline'},
 {k:'text',x:510,y:398,text:'Scheiben tragen eine Person · Streben tragen mehr',cls:'gmtxt',gm:true},
 {k:'text',x:510,y:262,text:'Wartungsflügel Nordseite: Kontakt → Alert +1',cls:'gmtxt',gm:true},
 // Glasdach Wintergarten
 {k:'line',x1:700,y1:40,x2:960,y2:230,cls:'glassline'},{k:'line',x1:960,y1:40,x2:700,y2:230,cls:'glassline'},
 {k:'text',x:830,y:205,text:'Lüftungsflügel: mechanisch, ohne Sensor, klemmt',cls:'gmtxt',gm:true},
 // East roof
 {k:'mast',x:880,y:300},{k:'text',x:880,y:342,text:'Antennen- & Blitzschutzmast'},
 {k:'rect',x:740,y:380,w:180,h:240,cls:'lz',gm:true},{k:'text',x:830,y:495,text:'Landezone Ost|flach · keine Kamera|Windschatten des Masts',cls:'gmtxt',gm:true},
 {k:'text',x:830,y:250,text:'Attika 1,1 m · Böen: im Freien Position Risky',cls:'gmtxt',gm:true},
 {k:'line',x1:948,y1:240,x2:948,y2:700,cls:'gateline'},{k:'line',x1:946,y1:620,x2:992,y2:620,cls:'vaultleaf'},
 {k:'rect',x:880,y:600,w:50,h:36,lbl:'BMU-|Steuerung',ly:612},
 {k:'text',x:938,y:470,text:'Schiene der Fassadenbefahranlage',rot:-90},
 {k:'arrow',x1:330,y1:530,x2:380,y2:530},{k:'text',x:355,y:548,text:'Wind aus SW'},
],
marks:[
 {n:1,x:60,y:555},{n:2,x:150,y:306},{n:3,x:150,y:380},{n:4,x:60,y:228},{n:5,x:600,y:300},{n:6,x:720,y:196},{n:7,x:850,y:662},{n:8,x:380,y:175},{n:9,x:760,y:366,gm:true},{n:10,x:270,y:250},
],
spots:[
 {n:1,t:'Skycab-Landeplattform',p:'Beleuchtete Plattform mit Wartehäuschen und Treppe hinunter in die Skycab-Lobby 112. Nachts landen hier autonome Skycabs mit VIP-Gästen.',g:'Der Anflugtransponder erteilt autonomen Skycabs die Landefreigabe: gehackt landet jedes Cab als „angemeldete Ankunft“; ohne Freigabe kreist es 90 Sekunden und meldet sich (Alert +1). Kamera am Häuschen. Landezone B für Fallschirme: eben, aber hell beleuchtet.'},
 {n:2,t:'Dachausstieg Personaltreppe',p:'Der einzige reguläre Weg aufs Dach: Stahltür, Reader.',g:'Alarmkontakt: Öffnen ohne Badge meldet still (Alert +1). Kamera und Bewegungsmelder davor. Die Treppe führt hinunter bis P2: 112 Wartungsgalerie, 111 Kernflur, an 110 vorbei (verriegelte Brandschutztür), EG-Lobby, Garage.'},
 {n:3,t:'Schachtkopf Technikschacht',p:'Unauffällige Luke zwischen den Technikaufbauten.',g:'Darunter der Wartungsschacht (80×80 cm) mit Steigleiter: Ausstiege auf 112 (Bodenluke Wartungsgalerie), 111 (Revisionstür Lager) und 110 (Löschzentrale). Kein Sensor bis 110. Der direkteste Weg vom Dach zur Vault, ohne die Party zu berühren.'},
 {n:4,t:'Drohnenport',p:'Lieferdrohnen landen hier und verschwinden in einem Schacht ins Gebäude.',g:'Drohnenschacht 40×40 cm bis zur Küche 111 und weiter in die Garage. Ein Rigger schickt Ausrüstung portionsweise hinunter oder hinauf. Der ständige Drohnenverkehr überdeckt kleine eigene Fluggeräte. Keine Kamera.'},
 {n:5,t:'Glasdach Atrium',p:'Beleuchtete Glaspyramide über dem Salon. Von unten sieht man jede Silhouette auf dem Glas.',g:'Streben tragen, Scheiben tragen eine Person. Wartungsflügel an der Nordseite mit Kontakt. Wer hier steht, wird bei Blitzen von unten gesehen (Consequence: ein Gast zeigt nach oben). Abseilen: 12 m bis zum Salonboden. Ein Sturz durch das Glas ist eine mögliche Consequence, nie das automatische Ergebnis.'},
 {n:6,t:'Glasdach Wintergarten',p:'Flacheres, dunkles Glasdach über dem Wintergarten.',g:'Lüftungsflügel mechanisch, ohne Sensor, klemmt (Prowl/Engineer). Darunter Venns Rückzugsort ohne Kamera, 5 m Abseilhöhe in weiche Pflanzen. Der leise Dacheinstieg.'},
 {n:7,t:'Fassadenbefahranlage (Gondel)',p:'Wartungskran mit Reinigungsgondel, geparkt an der Ostkante. Fährt auf einer Schiene an der Fassade.',g:'Steuerung manuell am Kasten oder per Interface. Die Gondel fährt an der Ostfassade bis zur Technischen Schleuse 110 (Andockpunkt) und weiter bis zum EG. Fahrten werden protokolliert; Abweichung vom Wartungsplan → stille Prüfung. Dragon’s Deal: „Sie bringt euch exakt ans Ziel und verriegelt sich danach außen.“'},
 {n:8,t:'Steigleiter',p:'Wartungsleiter an der Nordkante, hinunter zur Terrasse 111.',g:'8 m, Käfig oben verschlossen, außen herum kletterbar. Die Terrassenkamera zeigt nur den Drohnen-Landeplatz, nicht die Leiter. Wer hier ankommt, steht direkt neben der angelehnten Küchen-Servicetür.'},
 {n:9,t:'Landezone Ost',p:'',g:'Flaches Dach über der Suite, keine Kamera, Windschatten des Masts. Der beste Absprungpunkt für Fallschirm oder Gleiter. Achtung: Attika nur 1,1 m, Böen. Von hier zu Fuß um die Glaspyramide herum zum Dachausstieg.',gm:true},
 {n:10,t:'Technikaufbauten',p:'Kühltürme, Lüftungsgeräte, Notstrom. Laut, warm, dampfend.',g:'Deckung und Lärm. Notstrom/USV sabotieren löst Notbeleuchtung und Lockdown-Protokoll aus (Alert +2): schlechte Idee als Einstieg, gute Ablenkung bei der Flucht.'},
],
routes:[
 {id:'A',c:'public',pts:[[160,610],[220,660],[248,690]]},
 {id:'B',c:'staff',pts:[[200,326],[118,326]]},
 {id:'C',c:'tech',gm:true,pts:[[200,394],[118,394]]},
 {id:'D',c:'out',dash:true,pts:[[760,60],[760,120],[760,178]]},
 {id:'E',c:'out',dash:true,pts:[[905,650],[960,650],[979,660],[979,715]]},
 {id:'F',c:'out',dash:true,pts:[[350,165],[300,158],[282,152]]},
 {id:'G',c:'private',gm:true,dash:true,pts:[[830,440],[720,520],[360,520],[322,440],[322,330],[200,330],[114,320]]},
 {id:'H',c:'out',dash:true,pts:[[452,292],[500,340],[540,380]]},
],
routeText:[
 {id:'A',c:'public',t:'Skycab-Plattform → Treppe → Lobby 112',d:'Der offizielle Weg. Mit Buchung freundlich empfangen, ohne Buchung höflich befragt.'},
 {id:'B',c:'staff',t:'Dachausstieg → Personaltreppe',d:'Reader + Alarmkontakt + Kamera. Führt zu 112, 111 und weiter. Der Weg, den die Sicherheit erwartet.'},
 {id:'C',c:'tech',t:'Schachtkopf → Wartungsschacht',d:'Eng, dunkel, kein Sensor bis 110. Ausstiege auf 112, 111, 110. Der Weg um die Party herum.',gm:true},
 {id:'D',c:'out',t:'Glasdach Wintergarten → Wintergarten 111',d:'Flügel klemmt, kein Sensor, 5 m Seil in Pflanzen. Unten Venn ohne Kamera.'},
 {id:'E',c:'out',t:'Gondel → Technische Schleuse 110',d:'Außen an der Fassade hinunter. Protokolliert, sichtbar für Gäste an den Ostfenstern, aber sie umgeht das ganze Penthouse.'},
 {id:'F',c:'out',t:'Steigleiter → Terrasse 111',d:'8 m Leiter im Regen. Landet neben der Küchentür.'},
 {id:'G',c:'private',t:'Landezone Ost → um die Pyramide → Dachausstieg',d:'Zu Fuß über das Dach: Windschatten, dann offen. Kamera am Dachausstieg sieht euch kommen.',gm:true},
 {id:'H',c:'out',t:'Glasdach Atrium → Salon',d:'Spektakulär: Wartungsflügel, 12 m Seil mitten in die Party. Jeder sieht es. Nur bei vollem Alert oder als Auftritt.'},
],
sits:[
 '<b>Anflug ohne Freigabe.</b> Das Skycab kreist, die Gebäudesicherheit fragt nach. Mit gehackter Freigabe erwartet die Lobby-Wache „Gäste“ und hält die Tür auf.',
 '<b>Silhouetten.</b> Blitz über Seattle. Wer auf dem Atrium-Glas steht, wird von unten gesehen: „Ein Gast zeigt nach oben“ ist die Consequence, nicht sofort Alarm.',
 '<b>Böe.</b> Bei 4/5 im Freien: Ausrüstung rutscht Richtung Attika, der Gleiter verfängt sich am Mast, die Gondel schwankt. Harm oder verlorenes Equipment statt Alert.',
 '<b>Die Gondel fährt nur einmal.</b> Dragon’s Deal: exakt ans Ziel, danach verriegelt sie sich außen am Gebäude. Für die Flucht braucht die Crew etwas anderes.',
 '<b>Drei Wege nach unten.</b> Treppe (Alarmkontakt, Kamera), Wartungsschacht (eng, Sensor erst auf 110), Leiter (Terrasse, Küchentür). Die Wahl entscheidet, wo die Crew ankommt und wer sie sieht.',
],
};
