const LSCHNITT={
id:'schnitt',kind:'section',name:'Schnitt',short:'Schnitt',sub:'Alle vertikalen Verbindungen auf einen Blick',
aria:'Schematischer Schnitt durch die oberen Ebenen des Meridian Spire: 16 vertikale Verbindungen zwischen Tiefgarage, Erdgeschoss, Ebene 110, 111, 112 und Dach.',
chips:['16 vertikale Wege','6 öffentlich','4 Personal / Technik','3 privat oder verborgen','3 nur von außen','2 nur für Gegenstände'],
rows:[
 {id:'dach',label:'Dach',y:100},
 {id:'112',label:'112 · Lounge, Suite,|Skycab-Lobby',y:190},
 {id:'111',label:'111 · Gala-Ebene',y:280,fill:'public'},
 {id:'110',label:'110 · Tresorgeschoss',y:370,fill:'secure'},
 {id:'mid',label:'109 … 1',y:450,dash:true},
 {id:'eg',label:'EG · Lobby',y:520},
 {id:'p2',label:'P2 · Tiefgarage',y:590},
],
cons:[
 {n:1,name:'Glasaufzug',c:'public',stops:['eg','111'],pass:['mid'],who:'Gäste',from:'EG-Lobby',to:'111 Foyer',cost:'Einladung; Ankunft und Gesicht werden protokolliert',note:'Gästeliste'},
 {n:2,name:'VIP-Lobbyaufzug',c:'public',stops:['p2','eg'],who:'Gäste per Auto',from:'P2 VIP-Vorfahrt',to:'EG-Lobby',cost:'Auftreten; geprüft wird erst oben'},
 {n:3,name:'Frachtaufzug',c:'staff',stops:['p2','111'],pass:['mid','eg'],block:['110'],who:'Personal, Kisten',from:'P2 Frachtvorraum',to:'111 Kernflur',cost:'Badge + Scan; Halt auf 110 nur per Interface oder Rigger (Schachttür)',note:'110: kein Halt'},
 {n:4,name:'Personaltreppe',c:'staff',stops:['p2','eg','111','112','dach'],pass:['mid'],block:['110'],who:'Personal, Notfall',from:'P2',to:'Dach',cost:'Dachtür mit Alarmkontakt; 110 nur bei Feueralarm',note:'110: Brandschutztür'},
 {n:5,name:'Drohnenschacht',c:'tech',stops:['p2','111','dach'],pass:['mid','eg'],items:true,who:'nur Gegenstände',from:'P2 Depot',to:'111 Küche · Dach Drohnenport',cost:'40×40 cm; Rigger oder Hacker übernimmt eine Lieferdrohne',note:'40×40 cm'},
 {n:6,name:'Wartungsschacht',c:'tech',stops:['110','111','112','dach'],gm:true,who:'eine Person, eng',from:'Dach Schachtkopf',to:'110 Löschzentrale',cost:'Revisionstür 111, Bodenluke 112; Bewegungssensor erst auf 110',note:'SL'},
 {n:7,name:'Speiseaufzug',c:'tech',stops:['111','112'],items:true,who:'Gegenstände, sehr schlanke Runner',from:'111 Küche',to:'112 Pantry',cost:'60×60 cm; für Personen Desperate',note:'60×60 cm'},
 {n:8,name:'Freitreppe',c:'public',stops:['111','112'],who:'Gäste',from:'111 Salon',to:'112 Lounge',cost:'keine, aber jeder sieht, wer hinaufgeht'},
 {n:9,name:'Privattreppe',c:'private',stops:['111','112'],gm:true,who:'Veyrath',from:'112 Suite',to:'111 Arbeitszimmer',cost:'Suite-Reader, drei Bewegungsmelder; landet neben dem Privatlift',note:'SL'},
 {n:10,name:'Sammlerlift',c:'public',stops:['111','110'],who:'Venn, Wache, angemeldete Besucher',from:'111 Vorraum Galerie',to:'110 Schleuse',cost:'Reader + Anmeldung; die Schleuse zählt Personen'},
 {n:11,name:'Privatlift',c:'private',stops:['111','110'],gm:true,who:'Veyrath',from:'111 Arbeitszimmer',to:'110 Schleuse',cost:'Holzverkleidung; das Arbeitszimmer hat vier Türen',note:'SL'},
 {n:12,name:'Steigleiter',c:'out',stops:['111','dach'],pass:['112'],who:'Kletterer',from:'111 Terrasse',to:'Dach Nordkante',cost:'8 m im Regen, Käfig oben verschlossen, Kamera zeigt woandershin'},
 {n:13,name:'Skycab-Treppe',c:'public',stops:['112','dach'],who:'VIP per Luft',from:'112 Skycab-Lobby',to:'Dach Landeplattform',cost:'Buchung + Badge; Anflugtransponder hackbar'},
 {n:14,name:'Fassadengondel',c:'out',stops:['dach','110','eg'],pass:['112','111','mid'],who:'Rigger, Techniker',from:'Dach BMU',to:'110 Technische Schleuse · EG',cost:'protokolliert, von den Ostfenstern sichtbar; Dragon’s Deal: verriegelt sich danach',note:'Ostfassade'},
 {n:15,name:'Atrium & Glasdächer',c:'out',stops:['dach','112','111'],items:true,who:'Abseilen',from:'Dach Wartungsflügel',to:'112 Umgang · 111 Salon oder Wintergarten',cost:'Atrium: alle sehen es. Wintergarten: leise, 5 m in Pflanzen',note:'Seil'},
 {n:16,name:'Fassade Süd',c:'out',stops:['112','111'],items:true,who:'Abseilen',from:'112 Sky-Terrasse',to:'111 Privatbalkon',cost:'3 m seitlich, 5 m tiefer; unten Bewegungsmelder',note:'Seil'},
],
sits:[
 '<b>Jede Ebene hat mindestens drei Anschlüsse nach oben und unten.</b> Wird ein Weg gesperrt (Aufzug gestoppt, Tür verriegelt), zeige der Gruppe den Schnitt nicht, aber lass sie fragen: „Was gibt es noch?“ Die Antwort steht hier.',
 '<b>Zwei Wege führen nur Gegenstände.</b> Drohnenschacht und Speiseaufzug trennen Ausrüstung von Personen: Die Crew geht unbewaffnet durch den Bogen, die Waffen kommen über die Küche nach.',
 '<b>Ebene 110 ist die Engstelle.</b> Nur Sammlerlift, Privatlift, Wartungsschacht und Gondel erreichen sie regulär; Frachtaufzug und Treppe brauchen einen Trick (Interface, Feueralarm). Genau darum ist sie der Tresor.',
 '<b>Getrennte Crew.</b> Wenn die Gruppe sich trennt (Consequence), gib jedem Teil einen eigenen vertikalen Weg: einer im Frachtaufzug, eine auf der Steigleiter, einer in der Gondel. Sie treffen sich auf 110 aus drei Richtungen.',
],
};
