/* ---------- GM guide: English data ---------- */
const GUIDE_EN={
 ui:{title:'GM Guide',subtitle:'The run “Trial by Fire” step by step · Seattle 2080 · Meridian Spire',eyebrow:'Shadowrun · Feuerprobe · Runners in the Shadows',
  plans:'Meridian Spire plans',runner:'Runners & sheets',print:'Print',nav:'Flow',navDone:'done',doneLbl:'Section done',
  alert:'Alert clock',alertSub:'click segments',alertReset:'reset',alertNames:['Routine','Routine','Suspicion','Suspicion','Active alarm','Active alarm','Lockdown'],
  alertDesc:['Systems treat anomalies as normal event deviations. Drones patrol on standard patterns.','Systems treat anomalies as normal event deviations. Drones patrol on standard patterns.','Cameras cross-check more closely, doors ask for credentials again, staff are quietly questioned.','Cameras cross-check more closely, doors ask for credentials again, staff are quietly questioned.','Drones search actively, service routes are closed, elevators rerouted, identified runners are pursued.','Drones search actively, service routes are closed, elevators rerouted, identified runners are pursued.','Escape routes locked, external response called. Escalation, not failure.'],
  calc:'Payoff calculator',calcChecks:[['open','Case was opened (even expertly)'],['loot','Extra loot or damage to the collection'],['venn','Dr. Venn harmed'],['harm','Guests or staff injured or killed'],['gore','Indiscriminate killing despite orders']],
  calcNuyen:'nuyen',calcBase:'payout at alert {a}',calcHarm:'harm to people counts at least as high alert',calcLootCut:'damage to the collection cuts the payout further',
  verdictGood:'Ideal candidates. Veyrath will be in touch.',verdictMid:'Usable but risky. A follow-up job is possible, not certain.',verdictBad:'Not suitable. Breach of contract or greed; Veyrath withdraws.',
  portrait:'Portrait · click to insert',portraitRm:'remove',
  fine:'Fan material for the private gaming table. <i>Runners in the Shadows</i> is a Forged in the Dark game by Mark Cleveland Massengale; <i>Shadowrun</i> is a trademark of The Topps Company / Catalyst Game Labs. Meridian Spire, Vesperline Collections, Dr. Amara Venn, Dorian Kade, Veyrath and the living vault tissue are original creations for this one-shot. Portraits you insert here are stored only in your browser.'},

 npcs:[
  {id:'johnson',name:'Mr. Johnson',role:'Fixer · the face of the job',tags:['Human','Charcoal suit','Paper notebook'],kind:'person',
   bio:'A calm professional who keeps Veyrath’s contacts into the shadows. He arrives early, is already seated in the privacy booth when the crew shows up, and writes with a pen in a real paper notebook throughout the whole conversation. No visible commlink, no threats, no theatre. Johnson keeps agreements and expects the same.',
   look:['Charcoal-grey tailored suit, no insignia','Polite, factual, never hurried','Actually finishes his soykaf'],
   play:['States “unopened” matter-of-factly as one condition among several, without stressing it.','Does not haggle over agreed terms after the run.','Answers questions about his client with “My client values discretion.”'],
   secret:'Works directly for Veyrath and knows the run is a trial. He does not reveal it, but he does not lie clumsily either: anyone watching closely notices that he studies the crew like applicants.',
   say:'“The case is handed over closed. Nothing else in that room interests my client, and it should not interest you either.”'},
  {id:'venn',name:'Dr. Amara Venn',role:'Head curator of Vesperline Collections · the biometric key',tags:['Ork','Mid-40s','Left eye = biometrics'],kind:'person',key:true,
   bio:'Art historian and security curator. She is responsible for selection, provenance and the physical handover of the most valuable pieces, and one of the few people whose eye scan the vault accepts. Venn considers most guests people with too much money and too little understanding of art; genuine interest in a piece wins her attention at once. She wants to end the evening without incident and go home.',
   look:['Tall, slim, very upright posture, shaved head','Polished silver caps on both tusks','Left eye amber and natural; right eye a black cybereye without an iris','Dark green, severely cut evening suit, golden feather brooch'],
   play:['Mostly in the gallery; occasionally retreats to the winter garden.','Can register guests for a private viewing and escort them to the airlock.','Does not have the vault keycard and cannot open the vault alone.','Must not be harmed, per the contract. Abduction is possible but conspicuous.'],
   secret:'Knows nothing of the trial. Her suspicion is a good consequence: she asks follow-up questions, calls Kade over, or announces her departure when the party drags on.',
   say:'“You are actually looking at the piece, not the price tag. That is rare tonight. Come, let me show you why it hangs here.”'},
  {id:'kade',name:'Dorian Kade',role:'Head of security for the gala · knows the way to the keycard',tags:['Human','Cyberarms','Augmented reflexes'],kind:'person',
   bio:'Runs security for the evening and wants one thing above all: no visible incident in front of the VIPs. Kade is polite, calm and extremely attentive. He does not carry the vault keycard himself, but knows exactly where it sits in the black key box in the event office and how a legitimate withdrawal is logged. He authorises the release or assigns someone to do so.',
   look:['Elegant dark tailored suit over two flawlessly chromed cyberarms','Small, almost imperceptible twitches in hands, shoulders and gaze','Discreetly armed with a pistol'],
   play:['Source of information, obstacle or opportunity, never a mandatory waypoint.','Politely asks for identification instead of threatening.','Reacts to alert: on suspicion he asks questions, on active alarm he keeps guests away from endangered areas.'],
   secret:'Suspects nothing of the test. Anyone who gives him a plausible explanation can lower alert; anyone who deceives him gains an opponent with very fast reflexes.',
   say:'“I have nobody matching your description on the list. That need not mean anything. Help me clear it up before someone else does.”'},
  {id:'veyrath',name:'Veyrath',role:'Adult dragon · owner and true employer',tags:['Dragon','Collector','Not an antagonist'],kind:'dragon',
   bio:'A reserved, exceptionally wealthy collector who prefers to act through intermediaries rather than appear in public. The penthouse, vault, collection and briefcase are his; he stands behind Vesperline Collections and several shell companies. Veyrath regards runners as potentially valuable specialists and is looking for a small crew for later tasks. What interests him is reliability when greed, fear and improvisation collide.',
   look:['Appears only at the reveal: a vast shadow, wings in the rain','Speaks directly into the runners’ minds','Stays out of reach, blocks nothing, never attacks'],
   play:['Neither rescues nor hinders the crew. The building is the obstacle, not him.','Judges at the end: discipline, creativity, teamwork, control of escalation.','Values his property above metahuman life. That is deliberately uncomfortable.','Is never a combat encounter. If someone shoots at him, he ends the contact.'],
   secret:'Has allowed a difficult but realistically exploitable weakness in event mode for this one night. Collection, guests, staff and security are real. If the crew pulls off exceptional research, they may learn this beforehand; the reveal then becomes confirmation.',
   say:'“Call me Veyrath. The tower is mine. The vault is mine. And so is the case you have just stolen.”'},
 ],

 chapters:[
  {id:'blick',num:'At a glance',title:'What is really going on',time:'before the session',
   lead:'A one-shot for 3–4 players, three to four hours, Seattle 2080. The crew is to steal a briefcase from a private vault level during a gala. What they do not know: the vault belongs to the employer.',
   blocks:[
    ['tiles',3,[
      {h:'The job',sub:'public',ul:['Retrieve a black briefcase from the vault below the penthouse during the gala','Hand the case over <b>unopened</b>, take <b>nothing</b> else','Do not harm Dr. Amara Venn, avoid deaths','Access: physical vault keycard + Venn’s eye scan']},
      {h:'The truth',sub:'GM only',ul:['Penthouse, vault, collection and case belong to the dragon <b>Veyrath</b>','Mr. Johnson works for Veyrath; the run is a <b>trial by fire</b>','No rival dragon, no other owner, no hidden twist behind it','Veyrath neither intervenes nor rescues']},
      {h:'What is being tested',sub:'the yardstick',ul:['Understanding orders and taking them seriously','Solving unusual problems independently','Not escalating at once under pressure','Not stealing everything just because they can','Working as a team']}]],
    ['h3','Timetable for 3–4 hours'],
    ['table',['Section','Guide'],[['Character choice + short Shadowrun/RitS intro','15–25 min'],['Meeting Mr. Johnson','10–15 min'],['Gather information + plan','10–20 min'],['Entry and party','45–70 min'],['Vault level','45–70 min'],['Escape + reveal','20–35 min'],['Buffer','20–30 min']],[1]],
    ['p','If characters were chosen in advance, far more time remains for the mission itself. The chapters on the left follow the flow at the table; tick them off as you go. The alert clock and the payoff calculator accompany you through the whole run.'],
    ['note','gm','Guidelines',
     '<ul><li>No playbook and no single action is mandatory.</li><li>Keycard and eye scan are problems, not prescribed puzzles.</li><li>Veyrath tests the crew but never fudges a dice result and never becomes a combat encounter.</li><li>A full alert is escalation, not automatic failure. Consequences create new situations.</li><li>Competent runners need no roll for routine. Good ideas may bypass prepared scenes.</li><li>If the runners earn the truth about the employer, tell them.</li><li>For 3–4 hours: playability before completeness.</li></ul>'],
    ['h3','Key people'],
    ['npcs']]},

  {id:'einstieg',num:'Step 1',title:'Getting started at the table',time:'15–25 min',
   lead:'Choose characters, then cover world and rules in a few minutes. Nobody needs more before the first roll.',
   blocks:[
    ['h3','Shadowrun in five sentences'],
    ['p','Seattle 2080 is a city of vast corporations, extreme inequality, ubiquitous connectivity and real magic. Humans and metahumans live among AR advertising, cyberware, drones, spirits and privatised security. <b>Shadowrunners</b> do unofficial jobs for people who do not want to be linked to a deed; that is why the employer is called <b>Mr. Johnson</b>.'],
    ['ul',['You are competent professional criminals and may dare risky things.','The world is full of tech, Matrix and magic.','A good plan helps, but nobody plans every eventuality in advance.','When something goes wrong, a new complication arises instead of game over.']],
    ['h3','RitS in five minutes'],
    ['tiles',2,[
      {h:'Action roll',sub:'fiction first',p:'First the player describes what their runner does and wants. Only when something dangerous is at stake do you roll: as many d6 as the action rating, the highest counts.',ul:['<b>6</b> full success · <b>4/5</b> success with a consequence · <b>1–3</b> bad plus consequence','Several 6s: critical','Settle beforehand: <b>position</b> (controlled / risky / desperate) and <b>effect</b> (limited / standard / great)','Actions are not knowledge skills; they follow what the character actually does']},
      {h:'Edge & flashbacks',sub:'reserve and preparation',ul:['<b>2 edge</b>: push yourself, +1d or more effect','<b>1 edge</b>: assist a teammate, +1d','<b>Resistance roll</b> softens a consequence; it always works, the roll sets the edge cost','<b>Flashback</b>: mid-run, explain what you had prepared. The more elaborate, the more edge']}]],
    ['h3','Plan and engagement'],
    ['p','The group only picks a rough plan and names the required detail. Then comes the <b>engagement roll</b>, and you cut straight to the first interesting situation.'],
    ['chips',['Assault · point of attack','Deception · method','Social · connection','Stealth · entry point','Supernatural · power / method','Transport · route & means']],
    ['note','warn','Important','Do not let the group spend an hour planning around hypothetical security measures. Once plan and detail are set, the run begins. Everything else is a flashback.']]},

  {id:'johnson',num:'Step 2',title:'Meeting Mr. Johnson',time:'10–15 min',
   lead:'Calm, professional, no trap. The job is stated clearly, the conditions named plainly. This is where you set the yardstick the crew will later be measured against.',
   blocks:[
    ['h3','Recommended venue: “Raincheck”'],
    ['p','A 24-hour soykaf diner on a middle floor of a mixed-use high-rise. Rain runs in broad sheets down the panoramic windows. Most tables are empty; delivery drones wait outside on a charging rail. Johnson is already seated in a semi-transparent privacy booth, charcoal tailored suit, real paper notebook instead of a commlink.'],
    ['tiles',3,[
      {h:'Late ferry',sub:'alternative',p:'Johnson boards at a stop, sits next to the crew for ten minutes and vanishes into the crowd at the next landing.'},
      {h:'Parking deck above the clouds',sub:'alternative',p:'An almost empty automated car park in the upper floors of an office tower. Wind and rain whip through open sides while autonomous vehicles roll in and out without a word.'},
      {h:'Private Matrix lounge',sub:'alternative',p:'A rented virtual meeting room. For a first Shadowrun evening the physical option is better: the players get to know the real Sixth World first.'}]],
    ['h3','The briefing'],
    ['tiles',2,[
      {h:'The job',sub:'in Johnson’s words',p:'During tonight’s gala, retrieve a specific briefcase from the private vault beneath the penthouse of the Meridian Spire. Johnson provides a current photo of Dr. Venn and an exact description of the case.'},
      {h:'Conditions',sub:'the contract',ul:['The case is handed over <b>unopened</b>.','<b>Nothing else</b> is taken from the vault.','Dr. Amara Venn is <b>not harmed</b>.','No wetwork. Avoidable deaths are expressly unwanted.','How the crew proceeds is up to them.']},
      {h:'Known access factors',sub:'two keys',ol:['A physical vault keycard, somewhere in the penthouse during the gala.','The biometric eye scan of Dr. Amara Venn.']},
      {h:'Pay',sub:'recommended 6 nuyen',p:'A serious, professional run. 4 nuyen for a lighter tutorial feel, 8 only if the briefing should already hint at an exceptionally rich employer. Paid on handover per contract; Johnson does not haggle afterwards.'}]],
    ['note','gm','Do not foreshadow','Johnson names “unopened” plainly as one condition among several and does not stress the word. The hidden tamper protection is not hinted at in the briefing. Anyone who examines the case later on their own initiative can find clues.'],
    ['h4','What Johnson does not say'],
    ['ul',['That penthouse, vault and case belong to Veyrath himself.','That Veyrath is the true employer behind him.','That the job is a test.','That the security configuration deliberately leaves a chance.']],
    ['p','If the runners earn this information through credible research, do not hold it back artificially.']]},

  {id:'info',num:'Step 3',title:'Gather information',time:'10–20 min',
   lead:'One or two targeted questions per player are enough. The group only needs enough to settle plan and detail.',
   blocks:[
    ['qa',[
      {q:'When is security weakest?',a:'<p>During <b>event mode</b>. Between midnight and the end of the gala both access factors are on site at the same time. Afterwards the keycard leaves the building again and the vault goes into a stricter lockdown.</p>'},
      {q:'Where is the keycard?',a:'<p>In the service area there is a small, non-public <b>event office</b> where sensitive event equipment is kept during the gala.</p><p><b>On a particularly good result:</b> the card sits there in a black key box; withdrawal and return are logged.</p>'},
      {q:'How do I get close to Dr. Venn?',a:'<p>Venn mostly stays near the exhibited pieces and readily explains details to genuinely interested guests. She occasionally withdraws to a quieter <b>winter garden</b> to escape the small talk.</p>'},
      {q:'What gear stands out?',a:'<p>Guests may carry light personal gear. Big weapons, heavy armour and obvious operational equipment are hardly plausible in the glass elevator and become a problem at reception. <b>Service staff</b> can bring far bulkier crates and tools.</p>'},
      {q:'Is there an alternative way in?',a:'<p>An automated maintenance system runs along the outer façade with a small cleaning and inspection gondola. It can dock at a technical airlock near the penthouse.</p>'},
      {q:'What awaits us below the penthouse?',a:'<p>The vault level is normally unmanned. It works with sensors, airlocks and autonomous security drones.</p>'},
      {q:'What kind of building is this?',a:'<p>The ownership structure ends behind several opaque holdings. Vesperline Collections is only the visible management.</p><p><b>On exceptional research:</b> behind the structure stands the dragon <b>Veyrath</b>, and the penthouse with its vault is his. The later reveal still works: it turns from twist into confirmation that a dragon is testing the crew by having them break into his own property.</p>'}]],
    ['note','','Pacing lever','If the group debates too long, ask only: which plan? which detail? which load? Then engagement roll and cut.']]},

  {id:'plan',num:'Step 4',title:'Plan, engagement and entry',time:'transition',
   lead:'Once plan and detail are set, the engagement roll follows and you cut to the first serious situation. These approaches are offers, not solutions.',
   blocks:[
    ['table',['Plan','Possible detail'],[['Social','A genuine invitation through a contact'],['Deception','Catering crew with a forged shift assignment'],['Stealth','Maintenance airlock on the façade'],['Transport','Jump from an aircraft onto the roof'],['Supernatural','A concrete magical method of the runners'],['Assault','A technical access point the crew takes by force']]],
    ['p','A bad engagement does not mean the planning was stupid. It only means the first situation is already dangerous.'],
    ['h3','Possible approaches'],
    ['tiles',2,[
      {h:'As guests via the glass elevator',sub:'social · deception',pro:['Little attention once inside','Direct contact with Dr. Venn','Ideal for observation and deception'],con:['Invitation and identity must be plausible','Bulky gear stands out','The elevator logs arrivals'],fb:'Copied an invitation, got a name onto the guest list, stashed a weapon in the penthouse beforehand.'},
      {h:'As staff via garage and freight elevator',sub:'deception · stealth',pro:['Tools, crates and gear are plausible','Direct access to the service area and the keycard'],con:['Staff are separated by function and location','Unknown names stand out on rosters','Being in the wrong area looks suspicious fast'],fb:'Forged work ID, manipulated shift list, real uniform, delivery order.'},
      {h:'Jump onto the roof',sub:'transport · assault',pro:['Hardly any social prerequisites','Lots of gear possible','Spectacular for physical runners'],con:['Weather, wind, altitude','Visible approach; the glass roof can be seen from below','Wrong drop point, lost gear or harm as consequences'],fb:'A fall through the glass roof is a possible consequence, not the automatic result.'},
      {h:'Façade maintenance',sub:'stealth · rigger · hacker',pro:['Bypasses the main entrance','Tools and climbing gear look plausible','Docks at a technical airlock just below the penthouse'],con:['The gondola is building tech and is logged','Guests or cameras may see it','A wrong drive command stops or locks it'],fb:'Gondola route manipulated in advance, maintenance order injected, technician access bought.'}]],
    ['note','gold','The players’ own idea','If the plan is compatible with the established fiction, play it out. Chartered skycab, staged medical emergency, art transport, hijacked delivery drone swarm, unusual magic: good ideas may bypass planned areas completely.']]},

  {id:'party',num:'Step 5',title:'The party in the penthouse',time:'45–70 min',
   lead:'The gala is in full swing. Here the runners solve two problems, in any order: Dr. Venn’s eye scan and the vault keycard from the event office.',
   blocks:[
    ['h3','Atmosphere'],
    ['p','Glass, dark wood, living plants, AR sculptures and real art compete for attention. From the open atrium the lights of Seattle show between the clouds. Subtle music lies over conversations of corporate people, collectors, artists and people whose actual work nobody names openly. Service drones carry drinks. Security observes rather than intimidates. Everything is meant to look expensive, controlled and effortless.'],
    ['h3','Areas'],
    ['tiles',3,[
      {h:'Grand salon',sub:'level 111',p:'The social centre. Many guests, good cover in the crowd, but also many eyes.'},
      {h:'Exhibition gallery',sub:'Venn’s territory',p:'Dr. Venn spends most of her time here. Pieces are annotated in AR with provenance and value. The collector’s lift lies behind it.'},
      {h:'Winter garden',sub:'quiet',p:'Slightly apart. A good opportunity for private conversation or an inconspicuous biometric capture.'},
      {h:'Service area',sub:'kitchen · storage · event office',p:'Staff corridor, storage and the event office with the keycard in the black box. Guests stand out here.'},
      {h:'Private study',sub:'level 112',p:'Not part of the event. Behind a flush wooden panel lies the private lift to the vault level.'},
      {h:'Glass roof and roof access',sub:'exposed',p:'Visible from below. Spectacular but very conspicuous.'}]],
    ['h3','Dr. Venn and the eye scan'],
    ['p','The runners decide how to obtain the biometric factor. Important: <b>Venn does not have the keycard.</b> Even if the crew wins her over completely, the card remains a problem. First the player describes the action, from that follows the action rating; there is no “you must roll Interface here”.'],
    ['ul',['High-resolution capture of the left eye and preparation of a retinal duplicate.','Get Venn to look voluntarily into a scanner or optical device.','Arrange a private viewing of the collection.','Lure Venn to the access airlock under a pretext.','Sedate or abduct her: not automatic failure, just far more conspicuous and risky.','Magic, as far as the specific character is actually capable of it.']],
    ['tiles',2,[
      {h:'Private viewing',sub:'the social high road',p:'Venn may register selected guests and escort them to the antechamber. She legitimises the biometric part but cannot open the vault alone: four-eyes principle with a separately stored keycard.',ul:['Recon drones count and identify the registered persons','Sensors check for unregistered gear','Drones make sure nobody leaves the group','Deviations trigger re-authentication or a silent alarm'],fb:'The advantage is not “no security” but a better starting position: actions against the drones can be <b>controlled</b> instead of risky or desperate.'},
      {h:'To the airlock under a pretext',sub:'deception',p:'Venn only confirms her factor without believing she is conducting a viewing: an alleged climate fault on a sensitive piece, an automatic security notice, a faulty access attempt by an employee, a fault in the collection area.',ul:['Venn goes to the authentication point and scans','The door stays shut until the keycard is used','Venn may stand right next to them while the second factor has to appear','Waiting too long or contradictory statements make the drones suspicious'],fb:'A social success does not skip the vault level. It only changes how security classifies the runners at first.'}]],
    ['q','BIOMETRIC FACTOR: CONFIRMED · PHYSICAL FACTOR: PENDING','sys'],
    ['h3','The vault keycard and Dorian Kade'],
    ['p','The card is dark grey, unlabelled and shows a faintly iridescent hologram only when viewed directly. It sits in the event office in a black key box; withdrawal and return are logged. The security architecture deliberately separates biometrics and physical authorisation.'],
    ['p','Kade does not carry the card himself but knows exactly where it is and how a legitimate withdrawal works: he or a staff member he designates authorises the release, then it is checked back in. Possible approaches: bypass the box, copy the card, intercept a legitimate withdrawal, deceive Kade, fake an authorisation, or something else entirely.'],
    ['note','gm','Optional complication','For very socially strong groups: a second ork woman with a shaved head and silver tusk caps is on the guest list and can be mistaken for Venn from a distance. Better left out for a beginners’ one-shot.'],
    ['h3','Consequences at the party'],
    ['ul',['A security officer politely asks for identification.','A guest thinks they recognise a runner.','Dr. Venn becomes suspicious.','The keycard is temporarily removed from the event office.','A bulky equipment crate is to be inspected.','Alert +1 or +2.']],
    ['note','','If the party drags on','Dr. Venn announces she will leave soon (in about twenty minutes). A piece of art is to go back into the vault. Staff begin dismantling. Pick whatever follows logically from what has happened.']]},

  {id:'ebene110',num:'Step 6',title:'The vault level · level 110',time:'45–70 min',
   lead:'No living staff, but sensors, airlocks and drones. Do not run the level as a dungeon with ten rooms: four core areas are enough, the magical shell lies over them as an extra layer.',
   blocks:[
    ['p','Two regular lifts lead down: the <b>collector’s lift</b> behind the exhibition rooms and the <b>private lift</b> in Veyrath’s study. Both end in the same sequence. A narrow <b>maintenance shaft</b> from the service core offers an additional irregular access.'],
    ['chips',['Lift','Access airlock','Sensor corridor','Vault door','Collection']],
    ['tiles',2,[
      {h:'Access airlock',sub:'17.1',p:'Both lifts end in the same matte black airlock. A first sensor layer registers movement, weight and unauthorised devices. Venn’s presence or a valid registration only decides whether the group is first treated as expected visitors or as intruders.',ul:['Reported head count does not match','Conspicuous or unregistered gear','Someone separates from the group','Silent alarm, door locks behind the crew, cameras focus, additional identity check']},
      {h:'Sensor corridor',sub:'17.2',p:'Long, surprisingly empty, almost museum-like. Cameras, motion detectors, invisible light barriers, pressure sensors, local RFID and device scans. Not everything has to matter at once; first describe only what the runners perceive.',ul:['A sensor registers a deviation','A door closes behind the crew','A drone activates','Gear is flagged as a foreign device','Alert rises']},
      {h:'Drone node',sub:'17.3',p:'A service niche with the local drones and their maintenance ports. <b>Recon drones</b>: small, fast, observe and tag. <b>Guardian drones</b>: larger, armed, isolate and suppress; non-lethal options, lethal on massive escalation.',ul:['<b>Routine:</b> standard patrol, check irregularities','<b>Authorised viewing:</b> escort, count, compare; better position but watched','<b>Irregularity:</b> position themselves between suspects and vault, demand authentication, separate people; weapons only on further escalation'],fb:'Drones do not roll. Their behaviour runs through the runners’ action rolls and consequences. Beating them: Interface, sabotage, rerouting, locking in, precise shots at sensors, melee, spoofing target recognition, distraction, magic, or simply being faster.'},
      {h:'The vault door',sub:'17.4',p:'Two separate checks: read the keycard, confirm the eye scan within a short time. Order does not matter; the first factor opens a short window for the second. Every attempt is logged; a clean double access opens without alarm.',ul:['Venn does not have the keycard; her presence does not replace the physical factor','Without one or both factors access remains possible: manipulation, heavy tools, explosives, magic, flashback','It then gets louder, riskier or slower, not impossible']}]],
    ['h3','Magical shell of the vault'],
    ['p','The walls of the vault proper are threaded with cultivated living tissue: dark fibre strands like roots or muscle between the layers. It carries a <b>dual mana barrier</b> shielding physically and astrally. The tissue reacts to drilling and vibration, small wounds close, on alarm the fibres thicken. Damage is visible: fibres twitch, dark fluid seeps out. Outside the barrier an <b>astral watcher</b> may optionally patrol; it only reports and is not a mandatory opponent.'],
    ['note','','Chances for mage and adept','<ul><li><b>Assense</b> reveals mana barrier, watcher, magical traces and conspicuous objects in the collection.</li><li>A mage can study how the barrier opens in a controlled way at the regular doorway and gain an approach of their own.</li><li>An adept notices subtle environmental changes, danger, stress reactions or sensors earlier; with Assense or Astral Warrior they tackle astral problems directly.</li><li>Magical antiques can be told apart from mundane pieces.</li></ul>'],
    ['h3','Consequences on the vault level'],
    ['ul',['A drone gains visual contact.','An airlock locks.','A weapon or tool is damaged or lost.','Security foam fills a section and hampers movement and sight.','The direct way back is blocked.','The biometric copy only works partially; an additional step is needed.','Alert rises sharply.']],
    ['note','','If the level drags on','Reduce it to three beats: a sensor problem, a drone confrontation, the vault door. Everything else becomes description or consequence.']]},

  {id:'tresor',num:'Step 7',title:'The vault and the case',time:'climax',
   lead:'Not a bank room full of deposit boxes but the modern hoard of a dragon. The case lies unremarkably among things obviously worth more. This is where the decision Veyrath really cares about is made.',
   blocks:[
    ['h3','Veyrath’s modern dragon hoard'],
    ['p','The lights come up slowly: paintings from several centuries, sculptures and archaeological objects, old and modern melee weapons, high-end firearms, jewellery and historical gems, rare printed books, sealed data archives, single pieces of modern cyber- and biotechnology, several magical antiques and things whose value can hardly be judged without expert knowledge. Everything is curated; nothing lies around by chance. The black briefcase rests on a low plinth between far more conspicuous objects.'],
    ['note','gold','Temptation','At least one piece is obviously more valuable than the case and surprisingly easy to take: a small casket of historical gems, an ornate magical antique, a compact piece of cybertech. There is <b>no additional trap</b> on it. If the players want to take something, let them. The contract merely forbids it, and Veyrath will judge it very precisely later.'],
    ['h3','The briefcase'],
    ['tiles',3,[
      {h:'Exterior',sub:'visible to all',p:'About 45 cm wide, matte black ceramic composite, remarkably old-fashioned: no AR display, no data port, no logo, no radio signal. A single thin ivory line runs almost as a circle over lid and base, broken only at the handle by a finger’s width. Handle of dark metal wrapped in worn black leather. Over one latch a pale blue single-use tamper seal.'},
      {h:'Matrix',sub:'offline',p:'Transmits nothing, cannot be located via the Matrix. Its safeguards work locally without a radio link. In a vault full of networked, gleaming objects this silence seems almost provocatively plain.'},
      {h:'Magical',sub:'faint aura',p:'A faint, old magical aura. Not dangerous, triggers nothing, but makes the case stand out among the many objects for astrally perceiving characters.'}]],
    ['note','gm','Hidden tamper protection','<p>A small, professionally integrated <b>explosive charge</b> sits in the frame. If the case is fully opened without neutralisation, the charge primarily destroys the contents. Anyone holding it in front of them is in serious danger, but it is <b>not an automatic death trap</b>: harm, lost gear, an alarm or another consequence make more sense than a sudden character death.</p><p><b>Discoverable</b> on deliberate examination: unusual weight, a second inner frame, fine manufacturing gaps along the lid, a separate shielded circuit, chemical or technical traces. Survey, Study, Engineer or Interface may fit; nothing is prescribed. Neutralising is controlled under calm conditions, far riskier under time pressure with active drones.</p><p><b>Second safeguard:</b> an inconspicuous mechanical tamper indicator inside. Even after perfect defusal and clean closing, Veyrath can later tell that it was opened.</p><p>Whoever leaves the case closed as ordered never learns of any of this. It is not a mandatory scene and not a puzzle.</p>'],
    ['table',['Behaviour','Judgement'],[['Not opened','Job fulfilled exactly.'],['Safeguard found, neutralised, opened anyway','Technically impressive, but a clear order ignored.'],['Opened carelessly','Charge detonates; contents destroyed, situation escalates.']]],
    ['note','gm','Contents','A palm-sized, cracked disc of black obsidian. Not worthless, but its real value is not apparent to the runners. Why it matters to Veyrath stays open. He deliberately chose an object whose loss would be real but hardly painful for him; that is why the charge is not a dummy. The contents are not a plot device. The test is whether the crew respects the instruction although they could find out more.']]},

  {id:'flucht',num:'Step 8',title:'The escape',time:'20–35 min incl. reveal',
   lead:'Play it out in detail only if it is interesting or time remains. The alert level decides how much resistance the crew meets.',
   blocks:[
    ['tiles',3,[
      {h:'Glass elevator',sub:'elegant at low alert',p:'The crew rides down among unsuspecting guests while the city slides past the glass walls. At higher alert the elevator can be stopped, rerouted or checked.'},
      {h:'Freight elevator and garage',sub:'pragmatic',p:'A prepared vehicle waits below, one is acquired on the spot, or the crew flees on foot into the lower levels of the complex.'},
      {h:'Jump from the roof',sub:'spectacular',p:'Parachutes or wingsuits. Wind, pursuers and lost gear are good consequences without playing out every metre.'},
      {h:'Façade maintenance',sub:'reusable',p:'The gondola can be used again, manually overridden or serve as a waypoint for the descent.'},
      {h:'Skycab extraction',sub:'contacts · tech',p:'An autonomous skycab or small aircraft appears at a permitted or improvised outside position: real booking, fake VIP instruction, takeover, rigger or flashback.'},
      {h:'Own idea',sub:'always allowed',p:'If the group finds a plausible better way, let it work.'}]],
    ['h3','Consequences during the escape'],
    ['ul',['The preferred exit is closed.','An elevator stops on the wrong floor.','Gear has to be left behind.','A drone latches onto the crew.','The group is split up.','A jump or flight manoeuvre causes harm or loss of equipment.']],
    ['note','','Who shows up at full alert?','Deliberately just a <b>contracted external police provider</b> or a contractual response team. Whether that is Knight Errant or Lone Star is your call if you want to check it against a Seattle source. With plenty of time left, start a short response clock; otherwise the next big consequence is the arriving reinforcement.']]},

  {id:'enthuellung',num:'Step 9',title:'The reveal',time:'during the escape',
   lead:'During or right after the escape, not as a long monologue. No final boss, no new confrontation: solely the assessment of the test.',
   blocks:[
    ['p','A vast shadow glides over the façade. Wings beat in the rain. For a moment a real dragon flies or climbs at a clear distance beside the fleeing crew, far larger than anything they expected. It does not block their way and makes no move to attack. Then the runners hear its voice directly in their minds:'],
    ['q','“Call me Veyrath. The tower is mine. The vault is mine. And so is the case you have just stolen.”'],
    ['p','That makes it clear: they did not rob a rival. Veyrath himself sent them into his own vault. Depending on how things went, he adds:'],
    ['tiles',2,[
      {h:'Clean run',p:'“You take what you were given and leave what is not yours. Rare. So you are actually good for something.”'},
      {h:'Successful but chaotic',p:'“Not elegant. Not quiet. But you are still alive and the case is with you. That will do for now.”'},
      {h:'Lots of violence',p:'“Violence is a tool. Whoever uses the same tool for every problem is no craftsman.”'},
      {h:'Extra loot',p:'“I asked you for one object. You decided my property should raise your pay. I will remember that.”'},
      {h:'Opened case',p:'“Curiosity is valuable. So is discipline. Tonight you showed me which of the two wins with you.”'},
      {h:'Charge neutralised cleanly',p:'“Recognising the safeguard was good work. Having to overcome it was your own decision.”'}]],
    ['note','warn','No fight','Veyrath stays out of reach, does not threaten the crew and does not block their escape. If the runners shoot at him, he ends the contact and withdraws rather than turning the epilogue into a fight against an adult dragon.']]},

  {id:'payoff',num:'Step 10',title:'Payoff and assessment',time:'wrap-up',
   lead:'The base pay is 6 nuyen. Veyrath ties the actual payout to the crew’s professionalism. The calculator on the left applies the rule.',
   blocks:[
    ['table',['Alert at the end','Payout'],[['Low alert (0–1)','6 nuyen'],['Medium alert (2–5)','5 nuyen'],['High alert / lockdown (6)','3 nuyen']],[1]],
    ['p','Injured or dead guests and staff count <b>at least as high alert</b> for the payout. Seriously harming or killing Dr. Venn is additionally a clear breach of contract. Damage to the collection weighs even heavier for Veyrath than harm to people: damaged or additionally stolen pieces draw his marked displeasure and can cut the payout further.'],
    ['tiles',3,[
      {h:'Ideal candidates',sub:'follow-up jobs',ul:['Case unopened','No extra loot, collection undamaged','Venn unharmed','Little unnecessary violence','Problems solved creatively and as a team']},
      {h:'Usable but risky',sub:'maybe',ul:['Job done','Medium or high alert','Avoidable attention','Unnecessary but not catastrophic escalation']},
      {h:'Not suitable',sub:'no further contact',ul:['Case opened deliberately, even expertly','Contents destroyed by careless opening','Venn seriously harmed or killed','Collection damaged or extra loot taken','Indiscriminate killing despite clear orders']}]],
    ['p','This does not mean the characters were “played wrong”. It is this employer’s reaction to their decisions. Give the crew room at the payoff to react to the reveal.'],
    ['h3','Optional: heat per RitS'],
    ['p','For a pure one-shot skip this step. If the crew continues, heat is determined by the normal rules, not copied from the alert clock: 0 heat smooth & quiet, 2 contained, 4 loud & chaotic, 6 wild, plus situational modifiers for high-profile targets or killings. <b>Alert</b> is what security knows and does now. <b>Heat</b> is the long-term attention afterwards.']]},

  {id:'werkzeuge',num:'Tools',title:'Alert, consequences and pacing',time:'throughout the run',long:true,
   lead:'The alert clock replaces heat during the run. It rises when an action plausibly draws attention and can fall when the fiction allows it.',
   blocks:[
    ['h3','Alert clock · 6 segments'],
    ['stages',[{range:'0–1',name:'Routine',col:'var(--alert0)',items:['Anomalies count as normal event deviations','Drones patrol on standard patterns','No search for the runners']},{range:'2–3',name:'Suspicion',col:'var(--alert1)',items:['Cameras compare movements and identities more closely','Single doors ask for credentials again','Drones watch conspicuous areas','Staff are quietly questioned']},{range:'4–5',name:'Active alarm',col:'var(--alert2)',items:['Drones search actively','Service routes partly closed','Elevators stopped or rerouted','Guests kept away from endangered areas','Identified runners are pursued']},{range:'6',name:'Lockdown',col:'var(--alert3)',items:['Alarm counts as confirmed','Escape routes locked or controlled','External security or police provider called','Room to act remains, but clearly escalation']}]],
    ['p','Suspicion means <b>no automatic dice penalty</b>. The changed fiction influences position and effect of coming actions. If an action works directly on the clock, limited / standard / great effect maps to 1 / 2 / 3 segments.'],
    ['tiles',2,[
      {h:'When does alert rise?',sub:'a fitting consequence when …',ul:['a camera sees something','a sensor is triggered','a false identity is checked','a drone sends a warning','a guest raises the alarm','a door is forced open','shots or explosions are audible','a Matrix intrusion leaves a usable trace'],fb:'Not every failed roll raises alert. Equally possible: harm, lost gear, worse position, less effect, blocked exit, suspicious Venn, keycard moved elsewhere, a drone appears, group split up.'},
      {h:'Can alert fall?',sub:'tug-of-war clock',ul:['A runner credibly explains to a guard why the deviation was harmless','A camera sequence is replaced with older footage','A triggered sensor is disguised as a fault','A drone is intercepted before it reports','A manipulated door log looks like maintenance','A party incident explains noise or movement'],fb:'Nobody says “I roll to lower alert”. First it must be clear what the character does in the world. On success alert drops according to effect, or an imminent rise is prevented.'}]],
    ['note','','No hacker required','A hacker has many opportunities to prevent alert but no exclusive right to it. Social: redirect suspicion, keep staff busy. Deception: identity or work order. Physical: disable a sensor or drone before it transmits. Precision: destroy optics and weapon modules. Tech: cables, doors, local controls. Magic: perception or movement. Mobility: leave the area before the search closes in. Repeated hacks do not automatically get harder, only when the fiction gives a reason: a countermeasure is running, a trace has begun, a system was isolated.'],
    ['h3','Scenario-specific dragon’s deals'],
    ['deals',['The invitation is genuine. But someone at the party recognises your alias.','You get the perfect biometric scan. Dr. Venn will remember your face very precisely later.','The drone goes offline at once. Its last data burst, however, has already been sent.','The maintenance gondola takes you exactly to the target. Then it locks itself outside and is no longer available for the escape.','You reach the case without further resistance. In return the vault door closes behind you.']],
    ['h3','Spotlight for the playbooks'],
    ['table',['Playbook','Typical chances to shine'],[['Face','Invitation, contacts, a serious collector role, keeping Venn busy, defusing suspicion socially'],['Hacker','Guest lists, cameras, elevators, access logs, drones, building tech'],['Muscle','Protecting the group, heavy gear, non-lethal takedowns, forced emergency routes, drones in melee'],['Punk','Façade infiltration, parkour, distraction, sabotage, chaotic improvisation and escape'],['Rigger','Pilot for drop or escape, maintenance gondola, building drones, vehicles, remote control'],['Snake','Staff roles, disguise, deception, keycard theft, manipulating Venn'],['Trigger','Overwatch, spotting danger early, precisely disabling drone components, securing the exit'],['Adept','Depending on the way: perception, danger sense, mobility, physical infiltration; with fitting abilities astral problems'],['Mage','Assense the mana barrier and watcher, magical traces, telling magical objects apart, own workarounds'],['Techno','Influencing signals and networked systems emergently, manipulating drones or building tech, spotting anomalies']]],
    ['p','The run is not a character quiz. Nobody gets a room “just for their class”. The actions on the sheet matter more than the label.'],
    ['h3','Pacing'],
    ['tiles',2,[
      {h:'Planning too long?',ul:['Which plan are you using?','What is the detail?','Which load do you choose?','Then engagement roll and cut to the action.']},
      {h:'Plenty of time left?',ul:['Play the escape in more detail','Let a cut-off runner look for an alternative route','Response clock after full alert','Give the crew room at the payoff to react to the reveal']}]]]},

  {id:'referenz',num:'Appendix',title:'Quick reference',time:'for printing',
   lead:'Everything important at a glance when there is no time to flip pages at the table.',
   blocks:[
    ['qr',[
      {h:'The job',items:['<b>Steal:</b> the black case from the vault, unopened','<b>Hidden safeguard:</b> charge primarily destroys the contents on unauthorised opening; discoverable and defusable','<b>Tamper indicator:</b> opening stays provable even after defusal','<b>Do not steal:</b> anything else · <b>Do not harm:</b> Dr. Venn · <b>Avoid:</b> deaths','<b>Payoff:</b> 6 nuyen at low alert, 5 at medium, 3 at high; harm to people at least as high']},
      {h:'Access factors',items:['Vault keycard in the black box in the event office (service area)','Dr. Venn’s eye scan: left, amber, natural eye','Without one or both factors access remains possible, but louder, riskier, slower']},
      {h:'Penthouse 111/112',items:['Grand salon · exhibition gallery · winter garden','Service area with event office','Collector’s lift behind the exhibition rooms','Private study with private lift','Glass roof and roof access']},
      {h:'Vault level 110',items:['Shared access airlock','Sensor corridor','Drone node: recon and guardians','Vault door: keycard + eye scan, any order','Living vault shell with dual mana barrier, optional astral watcher','Modern dragon hoard with temptation']},
      {h:'Alert clock ○○○○○○',items:['<b>0–1</b> routine','<b>2–3</b> suspicion','<b>4–5</b> active alarm','<b>6</b> lockdown + external response']},
      {h:'NPCs',items:['<b>Mr. Johnson:</b> Veyrath’s professional fixer','<b>Dr. Amara Venn:</b> ork curator, left eye = biometrics, has no keycard','<b>Dorian Kade:</b> head of security, cyberarms, knows storage and release of the keycard','<b>Veyrath:</b> adult dragon, owner and employer, tests the crew, never fights']},
      {h:'The truth',items:['Veyrath owns penthouse, vault, collection and case and commissioned the break-in into his own vault','No rival dragon','The gala deliberately creates a realistic window','Tested: discipline, creativity, teamwork and control of escalation']},
      {h:'Dice',items:['<b>6</b> success · <b>4/5</b> with consequence · <b>1–3</b> bad · several 6s critical','Position: controlled / risky / desperate · effect: limited / standard / great','2 edge push, 1 edge assist, resistance costs edge','Flashback 0–2 edge depending on effort']}]]]},
 ],
};
