const RUNNERS=[
{
 id:'mercer',color:'face',pb:'Face',pbDesc:'Face: glatt, vernetzt, überall eingeladen',street:'Mercer',name:'Elias Mercer-Lund',meta:'Elf',idnShort:'SIN gesperrt · Fake',
 look:'Elf, Ende 30, silbergrau gefärbtes Haar, maßgeschneiderter Anzug in Anthrazit, ein einzelner Ohrring aus echtem Gold. Lächelt, bevor er spricht.',
 heritage:'Nordamerika · geboren in Tír Tairngire (Portland), seit 2071 in Seattle',
 background:'Corporate · Kunst-PR einer Konzerngalerie in Bellevue, nach einem Skandal gefeuert',
 vice:'Luxury · Chef Horowitz’ Privatdinner im Wilder-Hotel, Downtown',
 idn:'Eigene SIN existiert, ist aber gesperrt. Gefälschte SIN „Adrian Vale, Kunstberater“ (gute Qualität).',
 friendsLabel:'Shrewd Friends (kluge Freunde)',
 role:'Öffnet Türen, die andere aufbrechen müssten: Einladung, Gästeliste, Gespräch mit Dr. Venn. Der Grund, warum die Crew überhaupt in den Glasaufzug steigt.',
 feel:'Charme, Kontakte, Smalltalk mit Schlangen. Du redest, die anderen arbeiten im Schatten deines Lächelns.',
 actions:{consort:2,influence:2,study:1,survey:1,finesse:1},
 metaTraits:[['Low-light Vision','Du siehst bei schwachem Licht wie bei Tag.'],['Pointed Ears','Du hörst weiter als andere. 1 Edge: mehrere Minuten über normale Grenzen hinaus wahrnehmen (Flüstern im lauten Raum, Ultraschall).'],['Quick','Du bleibst bei Normal Load schnell.'],['Graceful','Widerstehst du einer Consequence aus sozialem Druck, kostet es dich nur 1 Edge, egal wie der Wurf ausgeht.']],
 cyber:'Keine Implantate. Mercer hält Chrom für einen Makel und lässt es sich anmerken. Dafür trägt er ein Kommlink der Oberklasse und Kontaktlinsen mit AR-Overlay.',
 karma:['Du hast eine Herausforderung mit Charisma oder Intrige gelöst.'],
 abilities:[{n:'Sprawl Whisperer',tag:'Start',t:'+1d auf Consort, wenn du vor einem Run Informationen über ein Ziel sammelst. Die Crew erhält +1d auf den Engagement Roll dieses Runs.'}],
 items:[
  {n:'Fine Outfit',l:0,rec:true,t:'Kleidung, die dich als wichtigen Manager, Offizier oder unbestrittenen Anführer ausweist, samt Abzeichen und Zubehör.'},
  {n:'Fine Nightlife Subscription',l:0,rec:true,t:'Vorausbezahltes Guthaben in den angesagten Clubs und Restaurants der Stadt. Macht betrunken und beeindruckt.'},
  {n:'Privacy Generator',l:1,rec:true,t:'Kleines Tischgerät für ein kurzes Gespräch ohne Abhörgefahr. Perfekt für fünf Minuten mit Dr. Venn im Wintergarten.'},
  {n:'Street Drugs',l:1,t:'Bis zu drei Dosen: Bluecoke, Glow, Nu-Ganja, Red Rock. Füllt sich in der Downtime von selbst wieder.'},
  {n:'Extra Fine Outfit',l:2,t:'Wie Fine Outfit, nur eine Stufe teurer: für Gala-Niveau.'},
  {n:'An Entourage',l:0,t:'Drei bis fünf Bodyguards, Fans und Bedienstete, nur dir loyal. Qualität = Tier, wenn sie helfen können.'},
 ],
 friend:{n:'Ines Okonkwo-Harada, Galeristin',t:'Kuratiert in Bellevue und schuldet Mercer noch etwas. Sie kann einen Namen auf die Gästeliste der Vesperline-Gala bringen oder sagen, welche Sammler heute dort sind.'},
 rival:{n:'Tobias Wren, Gesellschaftsreporter',t:'Schreibt für einen Trid-Klatschkanal, kennt jedes Gesicht der Szene und hat Mercers Sturz einst genüsslich begleitet. Er ist heute Abend eingeladen.'},
 why:'Mercer war einmal drin: die Einladungen, die Empfänge, die richtigen Leute. Ein Skandal, den er nicht verursacht hat, warf ihn hinaus. Sechs Nuyen sind gut, aber der eigentliche Lohn ist ein Abend, an dem er wieder oben steht. Und vielleicht der Name, der dahinter steckt.',
 shine:['<b>Foyer & Sicherheitsbogen:</b> Mit Fine Outfit und einem Namen von Ines wirst du durchgewunken. Sprawl Whisperer gibt der Crew +1d auf den Engagement Roll, wenn du vorher recherchiert hast.','<b>Galerie & Wintergarten:</b> Dr. Venn redet nur mit Leuten, die Kunst ernst nehmen. Consort 2 und Study 1 reichen, um eine private Besichtigung zu erbitten. Der Privacy Generator schafft fünf ungestörte Minuten.','<b>Alert senken:</b> Wenn eine Wache eine Abweichung sieht, lieferst du die plausible Erklärung, bevor sie zum Funkgerät greift.'],
 lore:{h:'SIN, Elfen und der Preis der Existenz',t:'Eine SIN (System-Identifikationsnummer) ist in der Sechsten Welt mehr als ein Ausweis: Konto, Wohnung, Krankenversicherung, Wahlrecht. Wer sie verliert, hört offiziell auf zu existieren. Mercer stammt aus Tír Tairngire, dem Elfenstaat südlich von Seattle, wo Abstammung über Karrieren entscheidet. Dass er heute mit Ork-Punks arbeitet, hätte sein Vater als Schande bezeichnet.'},
 gm:'Mercers echtes Gesicht steht seit dem Galerie-Skandal auf einer Bellevue-Sperrliste, die Kades Bogen mitprüft. Betritt er das Foyer ohne Verkleidung, gilt das als Abweichung (stille Prüfung, Alert +1). Tobias Wren ist der ideale Dragon’s Deal: „Die Einladung ist echt, aber jemand auf der Party erkennt deinen Alias.“ Mercer hat außerdem ein feines Gespür für Geld: Er ist der Erste, der spürt, dass hinter Vesperline jemand sehr Altes und sehr Reiches steht.',
},
{
 id:'chamaeleon',color:'snake',pb:'Snake',pbDesc:'Snake: Lügnerin, Manipulatorin, tausend Gesichter',street:'Chamäleon',name:'Lotte Brandt',meta:'Mensch',idnShort:'Fake-SIN',
 look:'Mensch, Anfang 30, unauffällig auf Wunsch. Heute: dunkler Hosenanzug, Brille ohne Stärke, Haare streng zurück. Morgen: jemand völlig anderes.',
 heritage:'Nordamerika · Los Angeles (Kalifornischer Freistaat), seit fünf Jahren Seattle',
 background:'Media · Stuntdouble und Nebendarstellerin in Trid-Serien, dann Schauspielunterricht für Leute, die nicht schauspielern wollten',
 vice:'Gambling · Krists Fight Clubs unter dem Kingdome-Gelände, Wetten auf alles, was sich bewegt',
 idn:'Keine eigene mehr. Gefälschte SIN wechselt mit der Rolle; die aktuelle lautet „Dr. Lena Voss, Kunstversicherung“ (siehe Fine Cover Identity).',
 friendsLabel:'Sly Friends (gerissene Freunde)',
 role:'Wird zu jemandem, der hier sein darf: Caterer, Versicherungsgutachterin, Sicherheitskraft. Holt die Keycard, ohne dass jemand merkt, dass sie geholt wurde.',
 feel:'Verkleidung, Täuschung, der Moment, in dem alle glauben, was du sagst. Du gewinnst Szenen, in denen niemand die Waffe zieht.',
 actions:{influence:2,consort:1,finesse:1,survey:1,study:1,prowl:1},
 metaTraits:[['Mensch','Keine besonderen Merkmale. Laut Regelwerk darfst du stattdessen bis zu zwei freie Permutationen wählen, um ein leichteres Leben abzubilden. Sprecht das mit der SL ab oder lasst es weg.']],
 cyber:'Ein unauffälliges Stimm-Modulator-Implantat im Kehlkopf (verändert Tonlage und Akzent) und eine Datenbuchse hinter dem Ohr für Simsense-Aufnahmen aus ihrer Trid-Zeit.',
 karma:['Du hast eine Herausforderung mit Täuschung oder Information gelöst.'],
 abilities:[{n:'Master of Disguise',tag:'Start',t:'Mit Verkleidung oder anderer verdeckter Irreführung erhältst du +1d auf Würfe, um Verdacht zu zerstreuen oder abzulenken. Wirfst du die Verkleidung ab, verschafft dir die Überraschung die Initiative in der Situation.'}],
 items:[
  {n:'Fine Disguise Kit',l:1,rec:true,t:'Pheromonfläschchen und Thermoplast-Maskenset mit Profi-Applikationen. Kann den Effect deiner Täuschungen erhöhen.'},
  {n:'Fine Cover Identity',l:0,rec:true,t:'Falsche Lizenzen, Holo-Visitenkarten, gestreute Gerüchte und Beziehungen: genug, um als andere Person durchzugehen.'},
  {n:'Concealed Holdout Pistol',l:0,rec:true,t:'Kleinkalibrig, im Ärmel verschwunden. Selbst bei einer Durchsuchung kaum zu finden.'},
  {n:'Blackmail Supplies',l:0,t:'Kompromittierende Aufnahmen, peinliche Videos oder belastende Beweise.'},
  {n:'Red Rock',l:0,t:'Eine Dosis: Das Opfer gleitet in einen ruhigen, suggestiblen Zustand, ähnlich einer Hypnose.'},
  {n:'Subterfuge Supplies',l:1,rec:true,t:'Standardausrüstung: Schminkkoffer, Subvokal-Kommunikator, Hausmeisteroutfit, Blanko-Lizenzen, Wendemantel.'},
 ],
 friend:{n:'Nadia Feld, Schichtplanerin bei Silberkante Catering',t:'Verkauft leere Schichtplätze bei Galas gegen Bargeld. Sie weiß, dass Silberkante heute den Meridian Spire beliefert und wie die Schichtliste auf dem Tablet der Leiterin aussieht.'},
 rival:{n:'Detective Marisol Ruiz, zuständiger Polizeidienstleister',t:'Hat Chamäleon vor zwei Jahren um Haaresbreite verpasst und sammelt seitdem jede Aufnahme einer Frau, die nirgends zweimal auftaucht.'},
 why:'Die Buchmacher wollen ihr Geld, und Chamäleon hat sich schon zu oft aus dem Staub gemacht. Aber ehrlich: Eine Gala, ein Tresor, eine Kuratorin mit Cyberauge und ein Koffer, den niemand öffnen darf. Das ist die beste Rolle, die ihr seit Jahren angeboten wurde.',
 shine:['<b>Tiefgarage & Frachtvorraum:</b> Mit Nadias Schichtplatz und Cateringuniform kommst du über die Laderampe hinein. Die Schichtleiterin scannt ihr Tablet: Master of Disguise gibt dir +1d, wenn sie stutzt.','<b>Eventbüro & Ausgabefenster:</b> In Sicherheitsuniform verlangst du die Keycard „auf Kades Anweisung für die Rückführung“. Influence 2, Risky. Bei 4/5 ruft die Eventmanagerin Kade an.','<b>Gäste-WC & Umkleide:</b> Als Gast hinein, als Personal hinaus. Fine Cover Identity trägt dich als Versicherungsgutachterin bis zu Dr. Venn.'],
 lore:{h:'Trideo, Simsense und gekaufte Identitäten',t:'Trid ist das Fernsehen der Sechsten Welt: dreidimensional, überall, mit Stars, die mehr Macht haben als Senatoren. Simsense geht weiter und überspielt Gefühle und Sinneseindrücke direkt ins Gehirn. Wer in dieser Welt berühmt war, weiß, wie billig Identität ist: Eine SIN kostet auf dem Schwarzmarkt weniger als ein gutes Abendessen, hält aber nur so lange, wie niemand genau hinsieht.'},
 gm:'Die Deckidentität „Dr. Lena Voss“ existiert wirklich: eine Züricher Kunstversicherin, mit der Dr. Venn schon E-Mails ausgetauscht hat. Venn wird höflich fragen, wie das Wetter in Zürich war. Ein Fehler hier macht Venn misstrauisch (Consequence), ein Erfolg öffnet die private Besichtigung. Detective Ruiz steht nicht im Spire, aber ihr Name eignet sich für die Heat-Abrechnung nach dem Run.',
},
{
 id:'kessel',color:'hacker',pb:'Hacker',pbDesc:'Hacker: digitaler Spion und virtuelle Waffe',street:'Kessel',name:'Rune Haldorsen',meta:'Zwerg',idnShort:'SIN-los · eigener Fake',
 look:'Zwerg, Mitte 20, breite Schultern, geflochtener Bart mit Datenkabel als Schmuck. Kapuzenjacke voller Sticker, darunter der Cyberdeck-Gürtel.',
 heritage:'Nordamerika · Puyallup, Seattle, im Schatten des Ash-Pit aufgewachsen',
 background:'Academic · Matrix-Informatik an der U-Dub, im dritten Semester geflogen, weil er das Notensystem der Fakultät umgeschrieben hat',
 vice:'Obligation · zwei jüngere Geschwister in Puyallup, deren Schulgeld und Klinikrechnungen er bezahlt',
 idn:'Nie eine echte gehabt. Seine gefälschte SIN hat er selbst gebaut; sie hält jeder Routineprüfung stand, aber keiner gezielten.',
 friendsLabel:'1337 Friends (elite Freunde)',
 role:'Gästeliste, Kameras, Aufzüge, Drohnen: alles, was ein Netz hat, ist deine Tür. Du siehst das Gebäude als Datenfluss und findest die Stelle, an der er stockt.',
 feel:'Matrix, Kameras, Schleusen und das Gefühl, das Gebäude atmen zu hören. Du bist selten dort, wo geschossen wird, und trotzdem überall.',
 actions:{interface:2,survey:1,engineer:1,study:1,prowl:1,consort:1},
 metaTraits:[['Thermal Senses','Du erkennst Wärmesignaturen in deiner Nähe, die normal unsichtbar wären.'],['Fun-sized','Du bist bei Light Load nicht schnell, bleibst aber bei Normal Load unauffällig. Man unterschätzt dich, und deine Statur.'],['Tenacious','Du erleidest erst eine Harm-Strafe, wenn eine ganze Zeile voll ist.'],['Thiccblood','Alkohol hängt dir nicht nach. Widerstehst du Gift oder Krankheit, kostet es nur 1 Edge.']],
 cyber:'Datenbuchse an der linken Schläfe, Cyberaugen mit Bildlink und Restlichtverstärker. Sein Cyberdeck „Kessel“ ist aus drei Konzernkommlinks zusammengelötet und trägt einen Anhänger seiner Schwester.',
 karma:['Du hast eine Herausforderung mit Information oder Cyberkriminalität gelöst.'],
 abilities:[{n:'Search Protocol',tag:'Start',t:'Du bist dir aller Online-Geräte in deiner Nähe stets bewusst. +1d, wenn du auf beliebige Weise Informationen über Hochtechnologie sammelst.'}],
 items:[
  {n:'A Scratch-Built Cyberdeck',l:1,rec:true,t:'Ein umgebautes Kommlink, das versteckte Datenspuren zeigt und leise ausnutzt. Merkmal: smart (kann nicht gegen dich gehackt werden).'},
  {n:'Suite of Warez',l:0,rec:true,t:'Illegale Apps fürs Cyberdeck: Armor, Arsenal, Breach, Mask. Mehrere Warez in einem Run ziehen Aufmerksamkeit.'},
  {n:'Blueprints',l:0,rec:true,t:'Datenbank mit Bauplänen und Stadtplänen. Sag beim Run, welche Pläne du geladen hast.'},
  {n:'Fine Surveillance Gear',l:1,t:'Signalscanner, Funk-Datenabgriffe, Tracer-Tags, Langstreckensensoren für Bild und Ton.'},
  {n:'VR Trodes',l:0,t:'Leichtes Stirnband für den Sprung in die virtuelle Realität ohne Datenbuchse.'},
  {n:'Portable VR Kit',l:1,t:'Flacher Koffer mit Sitz und Trodes: die sichere Ecke, aus der du das Gebäude übernimmst.'},
 ],
 friend:{n:'Glitch, Ex-Spinne für Gebäudeleittechnik',t:'Hat als Subunternehmerin die Aufzugsteuerung des Meridian Spire gewartet. Kennt den GLT-Verteiler in der Garage, den Wartungsplan der Fassadengondel und die Regel, dass der Frachtaufzug 110 nicht anfährt.'},
 rival:{n:'Nullpunkt, Konkurrenzhacker',t:'Verkauft dieselben Exploits an dieselben Leute, nur eine Stunde früher. Behauptet, Kessels Cyberdeck sei „ein Toaster mit Ambitionen“.'},
 why:'Die Klinik in Puyallup schickt Mahnungen. Sechs Nuyen tilgen den Rest. Und Glitch hat etwas gesagt, das ihn nicht mehr loslässt: „Ebene 110 hat einen eigenen Host. Niemand baut so etwas für Kunst.“',
 shine:['<b>Garage, GLT-Verteiler:</b> Von hier aus erreichst du Aufzüge, Türen und die Garagenkameras. Ebene 110 nicht, aber du kannst den Frachtaufzug dort anhalten lassen.','<b>Sicherheitsraum & Kameras:</b> Aufnahmen tauschen, einen Sensor als Defekt markieren: So sinkt Alert wieder. Search Protocol verrät dir, welche Drohne gerade sendet.','<b>Sicherheitsserver 110:</b> Physischer Zugriff auf Türen, Sensoren und Drohnenlogik der Ebene. Controlled, aber jeder Login wird protokolliert: Heat nach dem Run.'],
 lore:{h:'Die Matrix',t:'Die Matrix ist überall: als Augmented Reality über der Straße, als virtuelle Realität, wenn du dich per Trodes oder Datenbuchse einstöpselst. Konzerne betreiben Hosts, ihre Sicherheitshacker heißen Spinnen. Wer einbricht, riskiert Biofeedback, das den Körper verletzt. Kessel gehört zu den Deckern, die sich ihr Werkzeug aus Schrott bauen, weil ein legales Cyberdeck mehr kostet als eine Wohnung in Bellevue.'},
 gm:'Kessels Geschwister sind sein Hebel für Veyraths Gier-Test: Das kompakte Stück Cybertechnologie in der Sammlung ist genau die Prothesensteuerung, die seine Schwester braucht. Beschreibe es, wenn er den Koffer sieht. Glitch hat recht: Der Host von 110 ist vom Gebäudehost getrennt (Plan 110, Ort 8). Ein Hack von der Garage aus erreicht ihn nicht, ein physischer Zugriff im Serverraum schon.',
},
{
 id:'zephyr',color:'rigger',pb:'Rigger',pbDesc:'Rigger: Technikerin, Pilotin, Herrin der Drohnen',street:'Zephyr',name:'Sunny Delacroix',meta:'Mensch',idnShort:'SIN „gefallen“',
 look:'Mensch, Ende 30, sonnengegerbt, kurze Haare, Fliegerjacke mit abgetrennten Abzeichen. Am Nacken die Buchsen des Steuerimplantats, an der Hüfte immer ein Werkzeuggürtel.',
 heritage:'Nordamerika · Atlanta (CAS), Drohnenpilotin der UCAS-Armee, in Seattle hängen geblieben',
 background:'Military · Aufklärungs- und Transportdrohnen im Desert-Wars-Einsatz, unehrenhaft entlassen nach einer Befehlsverweigerung',
 vice:'Stupor · billiger Synthwhisky in der Hangar-Bar „Cap’s“ am Everett-Feld, nachts, wenn die Erinnerungen laut werden',
 idn:'Ihre echte Militär-SIN wurde beim Abschied auf „gefallen“ gesetzt. Für den Alltag hat sie eine gefälschte Zivil-SIN.',
 friendsLabel:'Handy Friends (praktische Freunde)',
 role:'Luftweg, Fassadengondel, Skycab, Drohnen im Schacht: Wo andere eine Tür suchen, siehst du einen Flugkorridor. Du bringst die Crew hoch und wieder runter.',
 feel:'Fahrzeuge, Drohnen und der Blick durch fremde Kameras. Dein Körper sitzt im Van, dein Kopf fliegt schon über dem Turm.',
 actions:{engineer:2,finesse:2,interface:1,survey:1,stalk:1},
 metaTraits:[['Mensch','Keine besonderen Merkmale. Laut Regelwerk darfst du stattdessen bis zu zwei freie Permutationen wählen. Sprecht das mit der SL ab oder lasst es weg.']],
 cyber:'Steuerimplantat (Control Rig) im Nacken, das sie direkt mit Drohnen und Fahrzeugen verbindet. Wenn sie „rigt“, sackt ihr Körper zusammen und atmet flach. Ihre linke Hand ist eine schlichte Prothese aus Armeebestand.',
 karma:['Du hast eine Herausforderung mit technischem Können oder Kontrolle gelöst.'],
 abilities:[{n:'Ace',tag:'Start',t:'Du kannst mit Finesse jedes Fahrzeug starten, steuern und landen, egal wie es angetrieben wird. Bei schwierigen Manövern erhältst du Potency.'}],
 items:[
  {n:'A Configured Drone',l:0,rec:true,t:'„Libelle“: handtellergroße Rotordrohne mit Kamera und Mikrofon, passt durch den Drohnenschacht. Weitere Merkmale kosten je eine Special-Item-Wahl.'},
  {n:'A Personal Vehicle',l:0,rec:true,t:'Ein schweres Motorrad mit Beiwagen, wartet in der VIP-Vorfahrt oder an der Rampe. Für zwei Personen, autonom fahrbar.'},
  {n:'Utility Harness',l:1,rec:true,t:'Drei Chemikalien oder Gadgets: Hypersolvent, Hyperglue, Thermite Gel, Nightshades, Sensor Tag, Spatial Scanner, Thermite Rod, Vehicular Override.'},
  {n:'Medical Supplies',l:1,t:'Drei Sprays oder Pflaster: Antidote Patch, Hard-Clot, Sterilizer, Stim Patch, Stun Patch.'},
  {n:'Fine Electrical Tools',l:1,t:'Lötkolben, Spezialschlüssel, Präzisionssensoren, Kopflampe mit Vergrößerung.'},
 ],
 friend:{n:'„Cap“ Okafor, Pilotin mit Kipprotor-Maschine',t:'Fliegt Frachtrouten über den Sound und hat keine Angst vor einem Überflug in 400 Metern. Sie setzt die Crew über dem Dach ab oder sammelt sie an der Ostfassade wieder ein.'},
 rival:{n:'Dispatcher Vance, Skycab-Leitstelle Seattle',t:'Hat Zephyr einmal dabei erwischt, wie sie ein Skycab ohne Freigabe umgeleitet hat. Er kennt ihre Signatur und meldet sie mit Vergnügen.'},
 why:'Zephyr will ihre alte Aufklärungsdrohne zurück, die ein Schrotthändler in Tacoma für zwölf Nuyen hält. Sechs sind ein Anfang. Und dieser Run hat Höhe, Wind und einen Turm, der einen echten Anflug verdient.',
 shine:['<b>Dach & Skycab-Plattform:</b> Mit Ace und Cap kommst du von oben. Der Anflugtransponder gibt gehackten Skycabs Landefreigabe; ohne Freigabe kreist das Cab und meldet sich.','<b>Fassadengondel:</b> Steuerkasten auf dem Dach, Andockpunkt auf 110. Finesse 2 für die Fahrt im Wind, Vehicular Override im Utility Harness für die Elektronik.','<b>Drohnenschacht:</b> „Libelle“ fliegt von der Garage in die Küche 111 und aufs Dach. Ausrüstung in Portionen, Augen überall, und niemand fragt eine Lieferdrohne nach der Einladung.'],
 lore:{h:'Rigger, Drohnen und die Kriege der Konzerne',t:'Ein Control Rig verbindet das Nervensystem direkt mit Maschinen: Die Riggerin fühlt den Rotor wie ihre eigene Hand. Solche Implantate kosten Essenz, ein Stück Menschlichkeit, das sich nicht zurückkaufen lässt. Die Desert Wars sind die Fernsehkriege der Konzerne, in denen Söldner vor Kameras kämpfen. Wer dort geflogen ist, kennt den Unterschied zwischen einem Ziel und einem Menschen.'},
 gm:'Zephyrs Control Rig ist registriertes Armee-Eigentum. Kades Sicherheitsbogen erkennt militärische Augmentierung und meldet sie still (Alert +1), falls sie durch das Foyer geht. Die Gondel-Fahrt ist der klassische Dragon’s Deal: „Sie bringt euch exakt ans Ziel und verriegelt sich danach außen.“ Cap fliegt zuverlässig, aber nur einmal: Ein zweiter Überflug zieht die Aufmerksamkeit der Luftraumüberwachung auf sich.',
},
