/* English layer: only text fields; numbers, names of items, abilities and traits stay as in the base data. */
const EN={
mercer:{
 street:'Mercer',pbDesc:'Face: smooth, connected, invited everywhere',idnShort:'SIN revoked · fake',
 look:'Late thirties, hair dyed silver-grey, tailored evening wear in charcoal, a single earring of real gold. You smile before you speak.',
 heritage:'North America · born in Tír Tairngire (Portland), in Seattle since 2071',
 background:'Corporate · art PR for a corporate gallery in Bellevue, fired after a scandal',
 vice:'Luxury · Chef Horowitz’s private dinners at the Wilder Hotel, Downtown',
 idn:'Your own SIN still exists but is revoked. A fake SIN under an alias of your choice, occupation art consultant, good quality.',
 friendsLabel:'Shrewd Friends',
 role:'Opens doors others would have to force: invitation, guest list, a conversation with Dr. Venn. The reason the crew gets into the glass elevator at all.',
 feel:'Charm, contacts, small talk with snakes. You talk; the others work in the shadow of your smile.',
 metaTraits:['You can see in low light as well as if it were well lit.','You hear from further away. Spend 1 edge to perceive beyond normal limits for several minutes (whispers in a noisy room, ultrasound).','You remain fast at normal load.','When you resist a consequence of social pressure, it costs only 1 edge, regardless of the roll.'],
 cyber:'No implants. You consider chrome a flaw and let people notice. Instead you carry a high-end commlink and contact lenses with an AR overlay.',
 karma:['You addressed a challenge with charisma or conspiracy.'],
 abilities:[{tag:'Start',t:'You gain +1d to Consort when you gather information on a target for a run. You get +1d to the engagement roll for that operation.'}],
 items:['A suit of clothes that marks you as an executive, an officer of rank or the undisputed leader of a gang, badges and accoutrements included.','Prepaid credit at the city’s popular clubs and restaurants. Intoxicates and impresses.','A small tabletop device for a short conversation free of audio surveillance. Perfect for five minutes with Dr. Venn in the conservatory.','Up to three doses: Bluecoke, Glow, Nu-Ganja, Red Rock. Refills itself during downtime.','Like the Fine Outfit, one step more expensive: gala level.','Three to five bodyguards, fans and retainers loyal only to you. Quality equals Tier when they can help.'],
 friend:{n:'Ines Okonkwo-Harada, gallerist',t:'Curates in Bellevue and still owes Mercer. She can put a name on the guest list of the Vesperline gala or tell you which collectors are there tonight.'},
 rival:{n:'Tobias Wren, society reporter',t:'Writes for a trid gossip channel, knows every face on the scene and once covered Mercer’s fall with relish. He is invited tonight.'},
 why:'You used to be inside: the invitations, the receptions, the right people. A scandal you did not cause threw you out. Six nuyen is good money, but the real payoff is one evening standing at the top again. And maybe the name behind it all.',
 shine:['<b>Foyer & security arch:</b> With the Fine Outfit and a name from Ines you get waved through. Sprawl Whisperer gives the crew +1d on the engagement roll if you did your research.','<b>Gallery & conservatory:</b> Dr. Venn only talks to people who take art seriously. Consort 2 and Study 1 are enough to ask for a private viewing. The Privacy Generator buys five undisturbed minutes.','<b>Lowering Alert:</b> When a guard spots a deviation, you deliver the plausible explanation before they reach for the radio.'],
 lore:{h:'SINs, elves and the price of existing',t:'A SIN (System Identification Number) is more than an ID in the Sixth World: bank account, apartment, health insurance, the right to vote. Lose it and you officially stop existing. Mercer comes from Tír Tairngire, the elven nation south of Seattle, where bloodline decides careers. That Mercer now works with ork punks counts as a disgrace in the family.'},
 gm:'Mercer’s real face has been on a Bellevue blacklist since the gallery scandal, and Kade’s arch checks it. If Mercer enters the foyer undisguised, that counts as a deviation (silent check, Alert +1). Tobias Wren is the perfect Dragon’s Deal: “The invitation is real, but someone at the party recognizes your alias.” Mercer also has a fine nose for money and is the first to sense that someone very old and very rich stands behind Vesperline.',
},
chamaeleon:{
 street:'Chameleon',pbDesc:'Snake: lies, manipulation, a thousand faces',idnShort:'fake SIN',
 look:'Early thirties, completely unremarkable on request. Today: dark suit, glasses without prescription, hair pulled back. Tomorrow: someone else entirely.',
 heritage:'North America · Los Angeles (California Free State), in Seattle for five years',
 background:'Media · stunt double and bit parts in trid series, then acting lessons for people who did not want to act',
 vice:'Gambling · Krist’s fight clubs under the Kingdome grounds, bets on anything that moves',
 idn:'None of your own anymore. The fake SIN changes with the role; the current one reads “Dr. L. Voss, art insurance” (see Fine Cover Identity). You choose the first name to fit the part.',
 friendsLabel:'Sly Friends',
 role:'Becomes someone who is allowed to be here: catering, insurance assessor, security. Fetches the keycard without anyone noticing it was fetched.',
 feel:'Disguise, deception, the moment everyone believes what you say. You win scenes in which nobody draws a gun.',
 metaTraits:['No special traits. By the rules you may instead pick up to two free permutations to represent an easier life. Talk it over with the GM or skip it.'],
 cyber:'An inconspicuous voice modulator in the larynx (changes pitch and accent) and a datajack behind the ear for simsense recordings from your trid days.',
 karma:['You addressed a challenge with deception or information.'],
 abilities:[{tag:'Start',t:'When you use a disguise or other form of covert misdirection, you get +1d to rolls to confuse or deflect suspicion. When you throw off your disguise, the resulting surprise gives you the initiative in the situation.'}],
 items:['A vial of pheromones and a thermoplastic mask kit with expert appliances. May increase the effect of your deceptions.','Fake licenses, business holo-cards, planted rumors and relationships: enough to pass as a different person.','Low calibre, vanished up a sleeve. Hard to find even in a search.','Compromising recordings, embarrassing video or incriminating evidence.','One dose: the victim slips into a calm, suggestible state, similar to hypnosis.','Standard gear: makeup kit, subvocal communicator, janitor outfit, blank licenses, reversible coat.'],
 friend:{n:'Nadia Feld, shift planner at Silberkante Catering',t:'Sells empty shift slots at galas for cash. She knows Silberkante is catering the Meridian Spire tonight and what the shift list on the supervisor’s tablet looks like.'},
 rival:{n:'Detective Marisol Ruiz, contracted police service',t:'Missed Chameleon by a hair two years ago and has collected every recording of a person who never shows up twice since.'},
 why:'The bookies want their money and you have skipped town too often already. But honestly: a gala, a vault, a curator with a cybereye and a case nobody may open. It is the best role you have been offered in years.',
 shine:['<b>Garage & freight lobby:</b> With Nadia’s shift slot and a catering uniform you come in over the loading dock. The shift supervisor scans her tablet: Master of Disguise gives you +1d when she hesitates.','<b>Event office & hatch:</b> In a security uniform you demand the keycard “on Kade’s orders for the return transport”. Influence 2, risky. On a 4/5 the event manager calls Kade.','<b>Guest restroom & locker room:</b> In as a guest, out as staff. Fine Cover Identity carries you as an insurance assessor all the way to Dr. Venn.'],
 lore:{h:'Trideo, simsense and identities for sale',t:'Trid is the television of the Sixth World: three-dimensional, everywhere, with stars more powerful than senators. Simsense goes further and plays feelings and senses straight into the brain. Anyone who was famous in this world knows how cheap identity is: on the black market a SIN costs less than a good dinner, but it only holds as long as nobody looks closely.'},
 gm:'The cover identity “Dr. Voss” really exists: a Zurich art insurer Dr. Venn has exchanged e-mails with. Venn will politely ask how the weather was in Zurich. A slip here makes Venn suspicious (consequence); a success opens the private viewing. Detective Ruiz is not in the Spire, but her name suits the Heat reckoning after the run.',
},
kessel:{
 street:'Kessel',pbDesc:'Hacker: digital spy and virtual weapon',idnShort:'SINless · own fake',
 look:'Mid twenties, broad shoulders, braided hair with a data cable as jewelry. Hoodie covered in stickers, the cyberdeck belt underneath.',
 heritage:'North America · Puyallup, Seattle, grew up in the shadow of the Ash Pit',
 background:'Academic · Matrix informatics at U-Dub, expelled in the third semester for rewriting the grading system',
 vice:'Obligation · two younger siblings in Puyallup whose school fees and clinic bills you pay',
 idn:'Never had a real one. You built the fake SIN yourself; it survives every routine check and no targeted one.',
 friendsLabel:'1337 Friends',
 role:'Guest list, cameras, elevators, drones: anything with a network is your door. You see the building as a data flow and find the spot where it stalls.',
 feel:'Matrix, cameras, airlocks and the feeling of hearing the building breathe. You are rarely where the shooting is, and still everywhere.',
 metaTraits:['Your senses detect nearby thermal signatures that are normally invisible.','You are not fast at light load, but you remain inconspicuous at normal load. People underestimate you, and your stature.','You do not suffer a harm penalty until an entire row is filled.','Alcohol does not linger. Resisting poison or disease costs only 1 edge.'],
 cyber:'Datajack at the left temple, cybereyes with image link and low-light amplifier. Your cyberdeck “Kessel” is soldered together from three corporate commlinks and carries a pendant from your sister.',
 karma:['You addressed a challenge with information or cybercrime.'],
 abilities:[{tag:'Start',t:'You are always aware of online devices in your presence. Take +1d when you gather information about high technology by any means.'}],
 items:['A modified comm that spots hidden data trails and quietly exploits them. Feature: smart (cannot be hacked to turn against you).','Illegal apps for the cyberdeck: Armor, Arsenal, Breach, Mask. Executing several warez in one run draws attention.','A database of architectural and city plans. Say which plans you loaded when the run starts.','Signal scanner, wireless data taps, tracer tags, long-range audio and video sensors.','A lightweight headband for entering virtual reality without a datajack.','A thin case with a seat and trodes: the safe corner from which you take over the building.'],
 friend:{n:'Glitch, former building-automation spider',t:'Maintained the elevator controls of the Meridian Spire as a subcontractor. Knows the building-control node in the garage, the maintenance schedule of the facade gondola and the rule that the freight elevator does not stop at 110.'},
 rival:{n:'Nullpunkt, Matrix competition',t:'Sells the same exploits to the same people, just an hour earlier. Claims Kessel’s cyberdeck is “a toaster with ambitions”.'},
 why:'The clinic in Puyallup keeps sending reminders. Six nuyen clears the rest. And Glitch said something that will not let you go: “Level 110 has its own host. Nobody builds that for art.”',
 shine:['<b>Garage, building-control node:</b> From here you reach elevators, doors and the garage cameras. Not level 110, but you can make the freight elevator stop there.','<b>Security room & cameras:</b> Swap footage, mark a sensor as defective: that is how Alert drops again. Search Protocol tells you which drone is transmitting right now.','<b>Security server 110:</b> Physical access to doors, sensors and drone logic of the level. Controlled, but every login is logged: Heat after the run.'],
 lore:{h:'The Matrix',t:'The Matrix is everywhere: as augmented reality over the street, as virtual reality when you plug in via trodes or datajack. Corporations run hosts; their security hackers are called spiders. Break in and you risk biofeedback that injures the body. Deckers like Kessel build their tools from scrap because a legal cyberdeck costs more than an apartment in Bellevue.'},
 gm:'Kessel’s siblings are the lever for Veyrath’s greed test: the compact piece of cybertechnology in the collection is exactly the prosthetic controller the sister needs. Describe it when Kessel sees the case. Glitch is right: the host of 110 is separate from the building host (plan 110, location 8). A hack from the garage cannot reach it; physical access in the server room can.',
},
zephyr:{
 street:'Zephyr',pbDesc:'Rigger: technology, flying skill, control over every machine',idnShort:'SIN “killed in action”',
 look:'Late thirties, sun-weathered, short hair, a flight jacket with the patches cut off. Control-rig jacks at the neck, always a tool belt at the hip.',
 heritage:'North America · Atlanta (CAS), drone missions for the UCAS Army, stuck in Seattle since',
 background:'Military · reconnaissance and transport drones in the Desert Wars, dishonorably discharged after refusing an order',
 vice:'Stupor · cheap synth whisky at the hangar bar “Cap’s” at Everett field, at night when the memories get loud',
 idn:'Your real military SIN was set to “killed in action” when you left. For everyday life you carry a fake civilian SIN.',
 friendsLabel:'Handy Friends',
 role:'Air route, facade gondola, skycab, drones in the shaft: where others look for a door, you see a flight corridor. You get the crew up and back down.',
 feel:'Vehicles, drones and the view through other people’s cameras. Your body sits in the van; your head is already flying over the tower.',
 metaTraits:['No special traits. By the rules you may instead pick up to two free permutations. Talk it over with the GM or skip it.'],
 cyber:'A control rig in the neck that links you directly to drones and vehicles. When you “rig”, your body slumps and breathes shallowly. Your left hand is a plain army-issue prosthesis.',
 karma:['You addressed a challenge with technical skill or control.'],
 abilities:[{tag:'Start',t:'You can Finesse a vehicle to take off, control or land it, regardless of its means of propulsion. You gain potency when you make difficult maneuvers while piloting a vehicle.'}],
 items:['“Dragonfly”: a palm-sized rotor drone with camera and microphone, fits through the drone shaft. More features cost one special item choice each.','A heavy motorcycle with sidecar, waiting at the VIP drop-off or the ramp. Seats two, drives autonomously.','Three chemicals or gadgets: Hypersolvent, Hyperglue, Thermite Gel, Nightshades, Sensor Tag, Spatial Scanner, Thermite Rod, Vehicular Override.','Three sprays or patches: Antidote Patch, Hard-Clot, Sterilizer, Stim Patch, Stun Patch.','Soldering irons, special wrenches, precision sensors, a headlamp with magnification.'],
 friend:{n:'“Cap” Okafor, tilt-rotor pilot',t:'Flies freight routes over the Sound and is not afraid of a pass at 400 meters. She drops the crew above the roof or picks them up again at the east facade.'},
 rival:{n:'Dispatcher Vance, Seattle skycab control',t:'Once caught Zephyr rerouting a skycab without clearance. He knows the control rig’s signature and reports it with pleasure.'},
 why:'You want your old reconnaissance drone back; a scrap dealer in Tacoma holds it for twelve nuyen. Six is a start. And this run has altitude, wind and a tower that deserves a proper approach.',
 shine:['<b>Roof & skycab pad:</b> With Ace and Cap you come in from above. The approach transponder grants hacked skycabs landing clearance; without clearance the cab circles and calls in.','<b>Facade gondola:</b> Control box on the roof, docking point on 110. Finesse 2 for the ride in the wind, Vehicular Override from the Utility Harness for the electronics.','<b>Drone shaft:</b> “Dragonfly” flies from the garage to the kitchen on 111 and up to the roof. Gear in portions, eyes everywhere, and nobody asks a delivery drone for an invitation.'],
 lore:{h:'Riggers, drones and corporate wars',t:'A control rig links the nervous system directly to machines: whoever rigs feels the rotor like their own hand. Such implants cost Essence, a piece of humanity that cannot be bought back. The Desert Wars are the televised wars of the corporations, mercenaries fighting in front of cameras. Anyone who flew there knows the difference between a target and a person.'},
 gm:'Zephyr’s control rig is registered army property. Kade’s security arch recognizes military augmentation and reports it silently (Alert +1) if Zephyr walks through the foyer. The gondola ride is the classic Dragon’s Deal: “It takes you exactly to the target and then locks itself to the outside of the building.” Cap flies reliably, but only once: a second pass draws the attention of airspace control.',
},
