{
 id:'bastion',color:'muscle',pb:'Muscle',pbDesc:'Muscle: gefährlich, einschüchternd, der Schild der Crew',street:'Bastion',name:'Gunnar Ekwueme',meta:'Troll',idnShort:'Konzern-SIN abgelaufen',
 look:'Troll, 2,40 m, ruhige Bewegungen, ein abgesägtes Horn (das andere poliert). Dunkler Mantel über schusssicherer Weste, Stimme wie ein Kühlschrank, der anläuft.',
 heritage:'Europa · Hamburg (Allianz Deutscher Länder), vor zehn Jahren mit einem Sicherheitsvertrag nach Seattle geholt',
 background:'Law · zwölf Jahre Konzernsicherheit und Personenschutz bei Sentinel Solutions, gefeuert, weil er einen Schießbefehl verweigerte',
 vice:'Obligation · seine Ex-Frau und die Tochter in Tacoma, deren Schulgeld er pünktlich überweist, egal was es kostet',
 idn:'Echte Konzern-SIN von Sentinel Solutions, mit der Kündigung ausgelaufen. Er hat sie nie ersetzt und wird deshalb bei jeder Kontrolle zum Problem.',
 friendsLabel:'Dangerous Friends (gefährliche Freunde)',
 role:'Steht zwischen der Crew und dem, was schiefgeht. Weiß, wie Sicherheitsleute denken, weil er einer war. Der Runner, der Gewalt beherrscht, statt sie zu brauchen.',
 feel:'Präsenz, Schutz, die Ruhe im Sturm. Du gewinnst, indem du die Crew heil herausbringst, nicht indem du Gegner zählst.',
 actions:{fight:2,command:1,wreck:1,survey:1,consort:1,study:1},
 metaTraits:[['Thermal Senses','Du erkennst Wärmesignaturen in deiner Nähe.'],['Oversized','Du bist nie unauffällig (auch nicht bei Light Load), dafür bei Heavy Load nicht langsamer und trägst +1 Load. Leute fürchten deinesgleichen.'],['Troll Armor','Haut und Knochen sind gehärtet: ein zusätzliches Armor-Kästchen und +1d auf Resistance Rolls mit Body.'],['Horned','Hörner als Waffe. Ein Horn hat er entfernen lassen, das andere macht Leute nervös.']],
 cyber:'Keine Implantate, aus Prinzip. „Ich habe genug Chrom in Gesichtern gesehen, die nichts mehr fühlten.“ Dafür Kevlar unter dem Mantel und eine Sicherheitslizenz, die noch aussieht wie echt.',
 karma:['Du hast eine Herausforderung mit Gewalt oder Zwang gelöst.'],
 abilities:[{n:'Bodyguard',tag:'Start',t:'Wenn du ein Teammitglied schützt, erhältst du +1d auf deinen Resistance Roll. Sammelst du Informationen, um Bedrohungen in der aktuellen Lage vorherzusehen, erhältst du +1 Effect.'}],
 items:[
  {n:'Light Armor',l:1,rec:true,t:'Leichter und unauffälliger als normale Panzerung, mit (echter oder gefälschter) Sicherheitslizenz. Passiert den Bogen im Foyer plausibel.'},
  {n:'Fine Scary Weapon/Tool',l:1,rec:true,t:'Schockhandschuhe: mehr Effect beim Einschüchtern, nicht mehr Schaden. Nichttödlich, wenn es sein muss.'},
  {n:'Containment Manacles',l:0,rec:true,t:'Selbstschließende Handschellen mit schlagfester Kette. Ein Souvenir aus der Sicherheitszeit.'},
  {n:'Fine Brutal Weapon',l:2,t:'Eine verheerende schwere Waffe, hier eine Schrotflinte aus Sentinel-Bestand. Potency, wenn Kraft oder Reichweite zählen.'},
  {n:'Kamikaze Vial',l:0,t:'Kampfdroge: Kraft, Schmerztoleranz, Wut für Minuten. Danach zwei Consequences: „Kann Freund nicht von Feind unterscheiden“ und „Hört nicht auf, bis alle liegen“.'},
  {n:'A Medieval Weapon',l:1,rec:true,t:'Standard: ein Teleskopschlagstock. Getting medieval, aber kontrolliert.'},
 ],
 friend:{n:'Doc Amsel, Straßenärztin in Tacoma',t:'Flickt Runner ohne Fragen und hat Bastions Horn amputiert. Sie kennt jeden Bodyguard der Stadt, der heute auf einer Gala Dienst hat.'},
 rival:{n:'Dorian Kade, Sicherheitschef der Gala',t:'War bei Sentinel Solutions Bastions Teamleiter und unterschrieb seine Kündigung. Kade hat ein Gedächtnis für Gesichter und zwei verchromte Arme, die Bastion nie mochte.'},
 why:'Bastion braucht das Geld für Tacoma, aber er nimmt den Job, weil Mr. Johnson sagte: kein Wetwork. Ein Run, bei dem niemand stirbt, in einem Turm, den Kade bewacht. Er will beweisen, dass man Sicherheit auch ohne Schießbefehl überwinden kann.',
 shine:['<b>Foyer & Sicherheitsbogen:</b> Light Armor mit Lizenz und Oversized bedeutet: Man sieht dich, aber man erwartet dich auch. Als angeheuerter Bodyguard eines Gasts bist du plausibel.','<b>Drohnenknoten 110:</b> Wächterdrohnen blockieren zuerst und schießen zuletzt. Bodyguard gibt dir +1d, wenn du dich vor die Crew stellst, und +1 Effect, wenn du ihre Zustände liest.','<b>Kade:</b> Du kennst seine Routine, seine Zuckungen, seinen Stolz. Consort oder Command, um ihn zu lesen, Survey, um seine Runde vorherzusagen. Solange er dich nicht sieht.'],
 lore:{h:'Trolle, Goblinisierung und Konzernsicherheit',t:'2021 verwandelten sich weltweit Menschen über Nacht in Orks und Trolle: die Goblinisierung. Trolle sind stark, gepanzert und leben mit Türen, Stühlen und Vorurteilen, die nicht für sie gebaut sind. Konzerne heuern sie gern als Sicherheit an und geben ihnen ungern Verantwortung. Ein Troll, der einen Schießbefehl verweigert, ist in den Schatten eine Legende und in Bellevue ein Fall für die Personalabteilung.'},
 gm:'Kade erkennt Bastion sofort, wenn er ihn unverkleidet sieht: keine Sirene, sondern ein Gespräch („Ekwueme. Ich dachte, Sie machen jetzt Nachtwache in Tacoma.“). Kade wird ihn danach nicht mehr aus den Augen lassen (Alert +1, eine Wache bleibt in Sichtweite), aber er könnte auch etwas fragen, das Bastion nützt. Bastions Test ist nicht Gier, sondern Ehre: Veyrath bewertet besonders, ob er Gewalt vermeidet, wenn Gewalt einfacher wäre.',
},
{
 id:'fizz',color:'punk',pb:'Punk',pbDesc:'Punk: gerissene Straßenkämpferin, Chaos mit Plan',street:'Fizz',name:'Kaya Rodriguez',meta:'Ork',idnShort:'SIN-los',
 look:'Ork, 19, drahtig, neongrüne Strähnen, eine Hauerkappe aus Sprühdosen-Aluminium. Kapuzenpulli, Kletterhandschuhe, Hoverboard unter dem Arm. Kaut ständig Kaugummi.',
 heritage:'Nordamerika · Redmond Barrens, Seattle. Nie weiter weg als Bellevue gewesen, und das nur zum Klauen.',
 background:'Underworld · Kurierin und Kletterin bei den Rusted Halos, einer Go-Gang, die sie verlassen hat, als der Anführer zu töten anfing',
 vice:'Pleasure · Dachpartys über dem Glow City, Adrenalin, laute Musik, alles, was nach Leben schmeckt',
 idn:'Keine. Nie gehabt. Für sie ist die Stadt eine Kletterwand ohne Ausweispflicht.',
 friendsLabel:'Shady Friends (zwielichtige Freunde)',
 role:'Nimmt die Wege, die es offiziell nicht gibt: Steigleiter, Wartungsschacht, Glasdach, Deckenhohlraum. Sorgt für Ablenkung, wenn es brenzlig wird, und ist als Erste wieder draußen.',
 feel:'Parkour, Improvisation, Sabotage und der Kick, gesehen zu werden und trotzdem zu entkommen.',
 actions:{prowl:2,finesse:1,wreck:1,survey:1,influence:1,fight:1},
 metaTraits:[['Low-light Vision','Du siehst bei schwachem Licht wie bei Tag.'],['Foolish Pride','Wirfst du bei einer Desperate Action ein Critical, erhältst du 1 Edge zurück.'],['Numbskull','1 Edge: ignoriere für eine Action eine Harm-Strafe, auch Kampfunfähigkeit.']],
 cyber:'Keine Implantate, aber Cyberaugen hätte sie gern. Dafür ein zerkratztes Kommlink mit Kletter-App, Gecko-Handschuhe und ein Hoverboard mit handgesprühten Flammen.',
 karma:['Du hast eine Herausforderung mit Überraschung oder Chaos gelöst.'],
 abilities:[{n:'Catch Me If You Can',tag:'Start',t:'Du darfst deine Special Armor ausgeben, um einer Consequence durch Entdeckung oder Sicherheitsmaßnahmen zu widerstehen, oder um dich für ein Kunststück der Flucht oder Heimlichkeit zu pushen.'}],
 items:[
  {n:'Gecko Gloves',l:1,rec:true,t:'Nanofaser-Handschuhe mit extremer Haftung: glatte und senkrechte Flächen erklimmen, Dinge sicher halten.'},
  {n:'Fine Stealth Outfit',l:1,rec:true,t:'Ganzkörperanzug aus Smart-Stoff, der dich in der Dunkelheit verschwinden lässt.'},
  {n:'Explosives',l:1,rec:true,t:'Drei elektronische Bomben am Gurt: Bangflash, EMP Grenade, Pepper Smoke, Tear Gas. EMP gegen Drohnen, Smoke gegen Kameras.'},
  {n:'Stunlock Vial',l:0,rec:true,t:'Betäubungsmittel für eine Stunde Schlaf. Ins Gesicht gesprüht wirkt es kurz, aber heftig.'},
  {n:'Fine Punk Stuff',l:1,t:'Ein kleines Hoverboard für Tricks, mit Grafiken deiner Wahl. Oder Stiefel mit Stacheln, oder eine Bauchtasche voller Murmeln.'},
  {n:'Climbing Gear',l:2,t:'Standard: Enterhaken, Saugnapfhandschuhe, Karabiner. Für alle, die keine Gecko Gloves haben.'},
 ],
 friend:{n:'Mondo, Fassadenreiniger der Wartungsfirma',t:'Fährt die Gondel des Meridian Spire jeden Dienstag. Er verrät, wo der Steuerkasten sitzt, wann der Wartungsplan eine Fahrt vorsieht und dass die Terrassenkamera nur den Drohnen-Landeplatz sieht.'},
 rival:{n:'Reißzahn, Anführer der Rusted Halos',t:'Nimmt es persönlich, dass Fizz gegangen ist. Seine Gang kontrolliert die Straßen um die Zufahrt nach Bellevue.'},
 why:'Ihr kleiner Bruder Teo ist elf und fängt an, die Rusted Halos cool zu finden. Sechs Nuyen sind eine Wohnung außerhalb der Barrens. Außerdem: 112 Stockwerke Glas. Fizz hat noch nie etwas so Hohes gesehen, das sie nicht bestiegen hat.',
 shine:['<b>Steigleiter & Wartungsschacht:</b> Von der Terrasse 111 zum Dach, vom Dach durch den Schacht bis auf 110, ohne die Party zu berühren. Catch Me If You Can zahlt für den Moment, in dem ein Sensor doch anschlägt.','<b>Deckenhohlraum:</b> Aus der Umkleide über die Trennwand ins Eventbüro. Eng, dunkel, genau dein Ding. Die Keycard liegt darunter in der Kassette.','<b>Ablenkung:</b> Pepper Smoke im Salon, ein Gast fällt in den Pool, ein Tablett kippt: Du kaufst der Crew die zwei Minuten, in denen niemand hinsieht.'],
 lore:{h:'Die Barrens, Go-Gangs und ein Leben ohne SIN',t:'Redmond war einmal ein Technologievorort. Heute sind die Barrens ein Stadtteil ohne Strom, Polizei oder Müllabfuhr, in dem Gangs die Ordnung sind. Wer hier geboren wird, hat oft keine SIN: keine Schule, kein Arzt, kein Weg hinaus außer den Schatten. Orks werden dort geboren, wo Menschen wegziehen. Fizz hält das nicht für Schicksal, sondern für eine Wand, die man hochklettern kann.'},
 gm:'Foolish Pride ist auch ein Charakterzug: Fizz kann einer Mutprobe nicht widerstehen. Die Schatulle mit Edelsteinen liegt in der Sammlung direkt neben der Tür und passt in ihre Bauchtasche. Beschreibe sie, bevor du den Koffer beschreibst. Mondos Wissen über die Gondel ist echt, aber jede Fahrt wird protokolliert (Plan Dach, Ort 7). Reißzahn kann bei der Flucht durch die Barrens als Response-Clock-Komplikation auftauchen.',
},
{
 id:'stille',color:'adept',pb:'Adept',pbDesc:'Adept: Magie im Körper, Perfektion als Weg',street:'Stille',name:'Jin Park',meta:'Mensch',idnShort:'Echte SIN',
 look:'Mensch, Anfang 30, schmal, sehr aufrecht, kurzes schwarzes Haar. Schlichte dunkle Kleidung ohne Logos, an Hals und Handrücken feine weiße Tätowierungen, die im Astralraum leuchten.',
 heritage:'Asien · Seoul, als Kind mit den Eltern nach Seattle; aufgewachsen zwischen zwei Sprachen und einem Dojo',
 background:'Academic · Philosophiestudium abgebrochen, zehn Jahre Kampfkunstlehrerin, dann Sicherheitsberaterin, die zu viele Verträge hinterfragte',
 vice:'Faith · Meditation im Dojo von Meister Oyelaran, Georgetown. Sie nennt es Disziplin; es ist eine Sucht nach Stille.',
 idn:'Echte, unauffällige SIN. Stille ist gemeldet, zahlt Steuern und existiert für den Staat als Kampfsportlehrerin.',
 friendsLabel:'Strange Friends (seltsame Freunde)',
 role:'Bewegt sich, wo Sensoren stehen, und spürt Gefahr, bevor sie eintritt. Liest Menschen wie einen Puls. Löst Konflikte mit einem Griff statt mit einer Kugel.',
 feel:'Wahrnehmung, Körperbeherrschung, ruhige Überlegenheit. Du bist die Figur, die die Falle sieht, bevor jemand hineinläuft.',
 actions:{prowl:2,finesse:1,fight:1,survey:1,study:1,stalk:1},
 metaTraits:[['Mensch','Keine besonderen Merkmale. Laut Regelwerk darfst du stattdessen bis zu zwei freie Permutationen wählen. Sprecht das mit der SL ab oder lasst es weg.']],
 cyber:'Keine Implantate: Cyberware würde ihre Magie schwächen. Ihre Tätowierungen sind Fine Mystic Body Art, ein Fokus, der ihren Weg trägt.',
 karma:['Du hast eine schwere Herausforderung mit innerer Vollkommenheit oder mystischer Kraft gelöst.'],
 abilities:[
  {n:'Practitioner of the Way',tag:'Pflicht',t:'Weg des Körpers (Fight, Finesse, Prowl, Wreck): Drei deiner Startpunkte liegen dort. Übernatürlichen Consequences widerstehst du mit Body. Du kannst nie Erwachte oder Emergente werden. Wähle einen Adepten-Drawback aus dem Regelwerk.'},
  {n:'Adept Senses',tag:'Start',t:'1 Edge: Für mehrere Minuten nimmst du über normale Grenzen hinaus wahr. Erkenne feine Veränderungen (Temperatur, Frequenz, Druck), spüre Gefahr, sei ein lebender Lügendetektor.'},
 ],
 items:[
  {n:'Fine Mystic Body Art',l:0,rec:true,t:'Tätowierungen, die deinen Adeptenkern bündeln. Supernatural gebunden, einzigartig, mühsam zu entfernen.'},
  {n:'Strange Trinket',l:0,rec:true,t:'Ein kleiner Gegenstand, hier eine abgenutzte Gebetskette, der Visionen der Vergangenheit oder nahen Zukunft eines Ortes zeigt, ob du willst oder nicht.'},
  {n:'Fine Astral Weapon',l:2,t:'Ein kurzer Stab, der gegen astrale Wesen wirkt. Für die Feuerprobe eher Ballast als Hilfe, außer der Watcher kommt näher.'},
  {n:'A Quiet Weapon',l:1,rec:true,t:'Standard: Wurfmesser oder ein Blasrohr mit Betäubungspfeilen. Leise, leicht, nichttödlich einsetzbar.'},
  {n:'Climbing Gear',l:2,t:'Standard: Enterhaken und Karabiner, falls Prowl 2 einmal nicht reicht.'},
 ],
 friend:{n:'Meister Oyelaran, Dojo-Leiter in Georgetown',t:'Trainiert die halbe Sicherheitsbranche von Seattle. Er weiß, welche Wachen heute im Spire stehen, wer davon augmentiert ist und wer nach einem 14-Stunden-Tag nachlässig wird.'},
 rival:{n:'Aurel Voss, Adept im Dienst einer Konzernsicherheit',t:'Trainierte einst neben Stille und hält ihren Weg für Schwäche. Er berät Sicherheitsfirmen in Bellevue, gelegentlich auch Vesperline.'},
 why:'Stille sucht Aufgaben, an denen sie wächst. Ein Turm voller Sensoren, Drohnen und einer Kuratorin, die nicht verletzt werden darf, ist eine Prüfung ihrer Disziplin. Das Geld geht ans Dojo. Der Test geht an sie selbst.',
 shine:['<b>Sensorkorridor 110:</b> Adept Senses spüren Lichtschranken als Wärme, Druckplatten als Unebenheit, Kameras als Summen. Prowl 2 trägt dich hindurch.','<b>Dr. Venn:</b> Als lebender Lügendetektor merkst du, ob sie misstrauisch wird, bevor sie es zeigt. Study, um sie zu lesen; Finesse, um den Iris-Scan unauffällig aufzunehmen.','<b>Glasdach Wintergarten:</b> Der Lüftungsflügel klemmt mechanisch, ohne Sensor. Fünf Meter Abseilen in weiche Pflanzen ist für dich ein Schritt.'],
 lore:{h:'Das Erwachen und die Adepten',t:'Seit 2011 ist Magie zurück in der Welt. Etwa einer von hundert Menschen ist erwacht: Magier zaubern und beschwören, Adepten lenken Mana in den eigenen Körper und werden schneller, wacher, härter, ohne dass man es sieht. Cyberware und Magie vertragen sich schlecht: Jedes Implantat kostet Essenz und schwächt die Gabe. Adepten wie Stille wählen deshalb den Körper, den sie haben, und machen ihn zur Waffe.'},
 gm:'Stilles Aura ist im Astralraum hell wie die eines Magiers. Der Watcher auf 110 bemerkt sie ebenso wie einen Zauberer (Alert +1 bei astraler Aktivität in seiner Nähe). Die Strange Trinket ist ein Werkzeug für Vorahnung: Vor der Tresortür kann sie eine Vision zeigen, in der ein gewaltiger Schatten über die Fassade gleitet. Ein leiser Vorgeschmack auf Veyrath, ohne den Twist zu verraten.',
},
{
 id:'ravn',color:'mage',pb:'Mage',pbDesc:'Magier: erwachter Hermetiker, Blick in den Astralraum',street:'Ravn',name:'Marek Sokolow',meta:'Ork',idnShort:'Konzern-SIN gekündigt',
 look:'Ork, Mitte 40, grau werdende Schläfen, sorgfältig gestutzter Bart über kräftigen Hauern. Tweedjacke, Lesebrille mit Sensorfokus, ein Ring aus Meteoreisen am kleinen Finger.',
 heritage:'Europa · Krakau, mit einem Konzernvertrag nach Seattle versetzt und dort geblieben',
 background:'Corporate · Wage Mage in der magischen Sicherheit eines Konzerns: Barrieren prüfen, Geister bannen, Dinge nicht hinterfragen. Er hinterfragte.',
 vice:'Weird · Gespräche mit „Vesna“, einem freien Geist, der in der leerstehenden Bibliothek am Pike Place wohnt und nur in Reimen antwortet',
 idn:'Seine Konzern-SIN wurde mit der Kündigung gelöscht. Er lebt mit einer gefälschten SIN als „Privatgelehrter“.',
 friendsLabel:'Strange Friends (seltsame Freunde)',
 role:'Sieht, was niemand sonst sieht: Barrieren, Watcher, magische Auren, den Koffer unter hundert Objekten. Zaubert leise und weiß, wie Konzernmagier denken.',
 feel:'Wissen, Astralraum, Zauber mit Bedacht. Du bist der Runner, der sagt: „Wartet. Da ist etwas an dieser Wand.“',
 actions:{study:2,consort:1,survey:1,influence:1,prowl:1},
 sup:{name:'Assense',dots:1,attr:'Awakened · zählt zu den 7 Punkten',gloss:'astral wahrnehmen, Barrieren und Geister lesen'},
 metaTraits:[['Low-light Vision','Du siehst bei schwachem Licht wie bei Tag.'],['Foolish Pride','Wirfst du bei einer Desperate Action ein Critical, erhältst du 1 Edge zurück.'],['Numbskull','1 Edge: ignoriere für eine Action eine Harm-Strafe, auch Kampfunfähigkeit.']],
 cyber:'Keine Implantate: Jedes Stück Chrom würde seine Magie schwächen. Sein Sensorfokus ist eine Brille, sein Zauberfokus der Ring aus Meteoreisen.',
 karma:['Du hast eine Herausforderung mit Wissen oder magischer Kraft gelöst.'],
 abilities:[
  {n:'Awakened',tag:'Pflicht',t:'Arkane Methode: hermetische Tradition (Drawbacks laut Regelwerk wählen). Du darfst Assense würfeln. Bei einer Desperate Assense-Action markierst du 1 Karma auf der Willpower-Leiste. Weitere Assense-Punkte kaufst du als Willpower-Aufstieg. Du kannst nie Emergenter oder Adept werden.'},
  {n:'Sorcerer',tag:'Start',t:'Du kennst die Methoden, metaplanare Energie durch deinen Körper zu leiten und Zauber zu wirken. Mit Study wirkst du eine Zauberformel und erzeugst einen übernatürlichen Effekt. Du startest mit zwei Zaubern.'},
 ],
 spells:{h:'Zwei gelernte Zauber',list:[
  {n:'Betäubungsblitz',t:'Ein Stoß Mana gegen den Geist eines Ziels: Ohnmacht statt Wunden. Nichttödlich, lautlos, sichtbar nur für Erwachte. Study, Reichweite Sichtlinie.'},
  {n:'Schleier',t:'Ein Trugbild über einer Person oder Sache: andere Kleidung, ein anderes Gesicht, ein Koffer, der wie eine Aktentasche aussieht. Hält, solange du dich konzentrierst; Kameras sind nicht getäuscht, Menschen schon.'},
 ]},
 items:[
  {n:'Fine Spell Focus',l:1,rec:true,t:'Der Ring aus Meteoreisen: Zauber mit außergewöhnlicher Kontrolle wirken.'},
  {n:'Fine Sensing Focus',l:1,rec:true,t:'Brille, durch die du arkane Energien in großem Detail siehst. Schützt auch etwas gegen Besessenheit.'},
  {n:'Banishing Focus',l:0,rec:true,t:'Ein kleines arkanes Amulett, dem astrale Wesen lieber aus dem Weg gehen.'},
  {n:'Fine Arcane Reagents',l:1,t:'Grabstaub, Gebetsperlen, erwachte Federn: konzentrierte Essenz für große Zauber, zerfällt nach Gebrauch.'},
  {n:'A Paracritter',l:0,t:'Ein erwachtes Tier als Begleiter (Cohort, Expert). Ravn hat keins; er behauptet, Vesna wäre eifersüchtig.'},
 ],
 friend:{n:'Talia Vance, Talismonger in Tacoma',t:'Handelt mit Foki und Reagenzien und hört alles, was Seattles Erwachte tratschen. Sie hat gehört, dass die Barriere im Meridian Spire von einem Meister gezogen wurde, den niemand kennt.'},
 rival:{n:'Dr. Henrik Solvay, Ravns alter Vorgesetzter',t:'Leitet weiter die magische Sicherheit seines Ex-Konzerns und hat Ravns Akte mit dem Vermerk „unzuverlässig, Verbleib beobachten“ versehen.'},
 why:'Ravn hat zwölf Jahre lang Barrieren für Leute gezogen, die ihm nie sagten, was dahinter lag. Jetzt will er einmal wissen, was hinter einer Wand ist, die so gut gebaut wurde. Die Nuyen zahlen Vesnas Bibliothek. Die Neugier zahlt er selbst.',
 shine:['<b>Vault 110:</b> Assense zeigt dir die duale Manabarriere, das lebende Gewebe und den Watcher auf seiner Runde. Am Türdurchgang siehst du, wie die Barriere kontrolliert geöffnet wird: ein Vorteil für jeden eigenen Weg hinein.','<b>Die Sammlung:</b> Der Koffer trägt eine schwache, alte Aura. Unter hundert glänzenden Dingen ist er für dich der einzige, der flüstert. Ebenso siehst du, welche Antiquitäten magisch sind und welche nur teuer.','<b>Betäubungsblitz & Schleier:</b> Eine Wache schläft, ein Runner sieht aus wie Personal, der Koffer wirkt wie eine Aktentasche. Nichttödlich, lautlos, genau nach Johnsons Bedingungen.'],
 lore:{h:'Hermetiker, Astralraum und Drachen',t:'Erwachte Magier folgen Traditionen: Hermetiker verstehen Magie als Wissenschaft mit Formeln und Kreisen, Schamanen als Beziehung zu Geistern und Mentoren. Der Astralraum ist die zweite Schicht der Welt, in der Gedanken Farben haben und Barrieren wie Mauern stehen. Ganz oben in dieser Welt stehen die Großen Drachen, uralt, unfassbar reich und in Konzernvorständen vertreten. Wer für Konzerne Magie gemacht hat, weiß: Manche Wände wurden nicht für Menschen gebaut.'},
 gm:'Ravn erkennt die Vault-Hülle als gezüchtete Dual-Barriere: eine Technik, die Jahrzehnte Zeit und ein Vermögen kostet. Kein Konzern baut so etwas für Kunst. Das ist die Spur zu Veyrath, ohne den Twist zu verraten. Vesna hat ihm vor dem Run in Reimen gesagt, der Turm „habe einen Herzschlag“. Der Watcher meldet astrale Aktivität (Alert +1), greift aber nicht an; Ravn kann ihn mit Assense ablenken oder still bleiben. Sein Ex-Vorgesetzter Solvay ist eine Heat-Komplikation für die Zeit nach dem Run.',
},
];
const CREWS=[
 {n:'Die Einladung',t:'Mercer (Face), Kessel (Hacker), Bastion (Muscle), Ravn (Magier). Über den Glasaufzug hinein, Venn im Gespräch, Kameras im Griff, ein Schild vor der Crew und ein Blick in den Astralraum.'},
 {n:'Die Leisen',t:'Chamäleon (Snake), Fizz (Punk), Stille (Adept), Kessel (Hacker). Als Personal durch die Garage, Keycard aus dem Eventbüro, Wartungsschacht nach 110, kein Schuss.'},
 {n:'Der Luftweg',t:'Zephyr (Rigger), Fizz (Punk), Bastion (Muscle), Stille (Adept). Von oben aufs Dach, Steigleiter und Schacht, Gondel zur Technischen Schleuse, Skycab zur Flucht.'},
 {n:'Drei Personen',t:'Mercer, Fizz und Ravn: Charme, Kletterei und Magie. Kessels Kameraarbeit ersetzt ihr durch Flashbacks und Fizz’ EMP-Granaten.'},
];
