bastion:{
 street:'Bastion',pbDesc:'Muscle: dangerous, intimidating, the crew’s shield',idnShort:'corporate SIN expired',
 look:'2.40 m, calm movements, one horn sawn off (the other polished). Dark coat over a bulletproof vest, a voice like a refrigerator starting up.',
 heritage:'Europe · Hamburg (Allied German States), brought to Seattle ten years ago on a security contract',
 background:'Law · twelve years of corporate security and close protection at Sentinel Solutions, fired for refusing a shoot order',
 vice:'Obligation · your ex and your daughter in Tacoma, whose school fees you transfer on time, whatever it costs',
 idn:'A real corporate SIN from Sentinel Solutions, expired with the dismissal. Never replaced, so every checkpoint is a problem.',
 friendsLabel:'Dangerous Friends',
 role:'Stands between the crew and whatever goes wrong. Knows how security people think because you were one. Masters violence instead of needing it.',
 feel:'Presence, protection, calm in the storm. You win by getting the crew out in one piece, not by counting opponents.',
 metaTraits:['Your senses detect nearby thermal signatures.','You are never inconspicuous (not even at light load), but you are not slower at heavy load and carry +1 load. People fear your kind.','Skin and bones are hardened: one extra armor box and +1d on resistance rolls with Body.','Horns as weapons. You had one removed; the other makes people nervous.'],
 cyber:'No implants, on principle. “I have seen enough chrome in faces that felt nothing anymore.” Kevlar under the coat instead, and a security license that still looks real.',
 karma:['You addressed a challenge with violence or coercion.'],
 abilities:[{tag:'Start',t:'When you protect a teammate, take +1d to your resistance roll. When you gather information to anticipate possible threats in the current situation, you get +1 effect.'}],
 items:['Lighter and less conspicuous than normal armor, with a (real or forged) security license. Passes the arch in the foyer plausibly.','Shock gloves: more effect when you intimidate, not more harm. Non-lethal when it has to be.','Self-latching manacles with impact-resistant chain. A souvenir from the security days.','A devastating heavy weapon, here a shotgun from Sentinel stock. Potency when power or reach matter.','Combat drug: strength, pain tolerance, rage for minutes. Then two consequences: “Can’t tell friend from foe” and “Can’t stop until they’re all broken”.','Standard: a telescopic baton. Getting medieval, but under control.'],
 friend:{n:'Doc Amsel, street doctor in Tacoma',t:'Patches up runners without questions and amputated Bastion’s horn. She knows every bodyguard in town who is on duty at a gala tonight.'},
 rival:{n:'Dorian Kade, head of security at the gala',t:'Was Bastion’s team leader at Sentinel Solutions and signed the dismissal. Kade has a memory for faces and two chromed arms Bastion never liked.'},
 why:'You need the money for Tacoma, but you take the job because Mr. Johnson said: no wetwork. A run where nobody dies, in a tower Kade guards. You want to prove that security can be beaten without a shoot order.',
 shine:['<b>Foyer & security arch:</b> Light Armor with a license plus Oversized means: they see you, but they expect you too. As a hired bodyguard of a guest you are plausible.','<b>Drone node 110:</b> Guardian drones block first and shoot last. Bodyguard gives you +1d when you put yourself in front of the crew and +1 effect when you read their states.','<b>Kade:</b> You know his routine, his twitches, his pride. Consort or Command to read him, Survey to predict his rounds. As long as he does not see you.'],
 lore:{h:'Trolls, goblinization and corporate security',t:'In 2021 people all over the world turned into orks and trolls overnight: goblinization. Trolls are strong, armored and live with doors, chairs and prejudices not built for them. Corporations like hiring them as security and dislike giving them responsibility. A troll who refuses a shoot order is a legend in the shadows and an HR case in Bellevue.'},
 gm:'Kade recognizes Bastion at once if he sees the character undisguised: no siren, but a conversation (“Well now. I thought you were doing night watch in Tacoma these days.”). Afterwards he does not let Bastion out of his sight (Alert +1, one guard stays in view), but he might also ask something useful to the crew. Bastion’s test is not greed but honor: Veyrath judges especially whether violence is avoided when violence would be easier.',
},
fizz:{
 street:'Fizz',pbDesc:'Punk: wily, streetwise, chaos with a plan',idnShort:'SINless',
 look:'19, wiry, neon-green streaks, tusk caps made from spray-can aluminium. Hoodie, climbing gloves, hoverboard under one arm. You chew gum constantly.',
 heritage:'North America · Redmond Barrens, Seattle. Never been further than Bellevue, and only to steal.',
 background:'Underworld · courier runs and climbing for the Rusted Halos, a go-gang you left when the leader started killing',
 vice:'Pleasure · rooftop parties above Glow City, adrenaline, loud music, anything that tastes like life',
 idn:'None. Never had one. To you the city is a climbing wall without ID checks.',
 friendsLabel:'Shady Friends',
 role:'Takes the routes that officially do not exist: access ladder, maintenance shaft, glass roof, ceiling void. Creates distractions when things get hot, and is the first one back outside.',
 feel:'Parkour, improvisation, sabotage and the thrill of being seen and getting away anyway.',
 metaTraits:['You can see in low light as well as if it were well lit.','Regain 1 edge when you roll a critical on a desperate action roll.','Spend 1 edge to ignore a harm penalty (including incapacitation) for an action.'],
 cyber:'No implants, but you would love cybereyes. Instead a scratched commlink with a climbing app, gecko gloves and a hoverboard with hand-sprayed flames.',
 karma:['You addressed a challenge with surprise or mayhem.'],
 abilities:[{tag:'Start',t:'You may expend your special armor to resist a consequence from detection or security measures, or to push yourself for a feat of escape or stealth.'}],
 items:['Nanofiber gloves with extreme adhesion: climb smooth and vertical surfaces, hold things securely.','A full bodysuit of smart cloth that blends you into the darkness.','Three electronic bombs on a strap: Bangflash, EMP Grenade, Pepper Smoke, Tear Gas. EMP against drones, smoke against cameras.','Tranquilizer for an hour of sleep. Sprayed in the face it works briefly but hard.','A small hoverboard for tricks, with graphics of your choice. Or spiked boots, or a fanny pack full of marbles.','Standard: grappling hooks, suction gloves, carabiners. For anyone without gecko gloves.'],
 friend:{n:'Mondo, facade cleaner for the maintenance firm',t:'Rides the Meridian Spire’s gondola every Tuesday. He tells you where the control box sits, when the schedule calls for a run and that the terrace camera only sees the drone pad.'},
 rival:{n:'Ripfang, leader of the Rusted Halos',t:'Takes it personally that Fizz left. His gang controls the streets around the approach to Bellevue.'},
 why:'Your little brother Teo is eleven and starting to think the Rusted Halos are cool. Six nuyen is an apartment outside the Barrens. Besides: 112 floors of glass. You have never seen anything that tall that you have not climbed.',
 shine:['<b>Access ladder & maintenance shaft:</b> From the terrace on 111 to the roof, from the roof down the shaft to 110, without touching the party. Catch Me If You Can pays for the moment a sensor trips after all.','<b>Ceiling void:</b> From the locker room over the partition wall into the event office. Tight, dark, exactly your thing. The keycard lies below in its box.','<b>Distraction:</b> Pepper smoke in the salon, a guest falls into the pool, a tray tips over: you buy the crew the two minutes in which nobody is watching.'],
 lore:{h:'The Barrens, go-gangs and life without a SIN',t:'Redmond used to be a tech suburb. Today the Barrens are a district without power, police or garbage collection, where gangs are the order. Those born here often have no SIN: no school, no doctor, no way out except the shadows. Orks are born where humans move away. Fizz does not consider that fate, but a wall you can climb.'},
 gm:'Foolish Pride is also a character trait: Fizz cannot resist a dare. The jewel casket lies in the collection right next to the door and fits in the fanny pack. Describe it before you describe the case. Mondo’s knowledge of the gondola is real, but every ride is logged (roof plan, location 7). Ripfang can show up as a response-clock complication during the escape through the Barrens.',
},
stille:{
 street:'Hush',pbDesc:'Adept: magic in the body, perfection as a path',idnShort:'real SIN',
 look:'Early thirties, slim, very upright, short black hair. Plain dark clothes without logos; fine white tattoos on neck and the backs of the hands that glow in astral space.',
 heritage:'Asia · Seoul, moved to Seattle with your parents as a child; grew up between two languages and a dojo',
 background:'Academic · dropped philosophy, taught martial arts for ten years, then security consulting until too many contracts raised questions',
 vice:'Faith · meditation at Master Oyelaran’s dojo in Georgetown. You call it discipline; it is an addiction to stillness.',
 idn:'A real, unremarkable SIN. You are registered, pay taxes and exist for the state as someone who teaches martial arts.',
 friendsLabel:'Strange Friends',
 role:'Moves where sensors stand and senses danger before it arrives. Reads people like a pulse. Solves conflicts with a grip instead of a bullet.',
 feel:'Perception, body control, quiet superiority. You are the one who sees the trap before anyone walks into it.',
 metaTraits:['No special traits. By the rules you may instead pick up to two free permutations. Talk it over with the GM or skip it.'],
 cyber:'No implants: cyberware would weaken your magic. Your tattoos are Fine Mystic Body Art, a focus that carries your way.',
 karma:['You addressed a tough challenge with inner perfection or mystical power.'],
 abilities:[{tag:'Required',t:'Way of the Body (Fight, Finesse, Prowl, Wreck): three of your starting dots lie there. You resist supernatural consequences with Body. You can never become Awakened or Emergent. Choose an adept drawback from the rulebook.'},{tag:'Start',t:'Spend 1 edge to perceive beyond normal limits for several minutes. Detect subtle environmental changes (temperature, frequency, pressure), sense the presence of danger, become a living lie detector.'}],
 items:['Tattoos that focus your adept core. Supernaturally bonded, unique, painstaking to remove.','A small item, here a worn prayer chain, that shows visions of the past or near future of a place, whether you want them or not.','A short staff effective against astral beings. For the Trial by Fire more ballast than help, unless the watcher comes closer.','Standard: throwing knives or a blowgun with tranquilizer darts. Quiet, light, usable non-lethally.','Standard: grappling hooks and carabiners in case Prowl 2 is not enough for once.'],
 friend:{n:'Master Oyelaran, dojo owner in Georgetown',t:'Trains half of Seattle’s security industry. He knows which guards stand in the Spire tonight, which of them are augmented and who gets careless after a 14-hour day.'},
 rival:{n:'Aurel Voss, adept in the service of a corporate security firm',t:'Once trained beside Hush and considers this path a weakness. He advises security companies in Bellevue, occasionally Vesperline too.'},
 why:'You seek tasks that make you grow. A tower full of sensors, drones and a curator who must not be harmed is a test of your discipline. The money goes to the dojo. The test is yours.',
 shine:['<b>Sensor corridor 110:</b> Adept Senses feel light barriers as warmth, pressure plates as unevenness, cameras as a hum. Prowl 2 carries you through.','<b>Dr. Venn:</b> As a living lie detector you notice her turning suspicious before she shows it. Study to read her; Finesse to capture the iris scan unnoticed.','<b>Conservatory glass roof:</b> The vent flap sticks mechanically, no sensor. Five meters of rope into soft plants is a step for you.'],
 lore:{h:'The Awakening and the adepts',t:'Magic has been back in the world since 2011. About one in a hundred people is Awakened: mages cast and summon, adepts channel mana into their own bodies and become faster, more alert, harder, without anyone seeing it. Cyberware and magic do not mix: every implant costs Essence and weakens the gift. Adepts like Hush therefore choose the body they have and make it the weapon.'},
 gm:'Hush’s aura is as bright in astral space as a mage’s. The watcher on 110 notices it just like a sorcerer (Alert +1 for astral activity nearby). The Strange Trinket is a tool for foreboding: in front of the vault door it can show a vision of a huge shadow gliding across the facade. A quiet foretaste of Veyrath without giving away the twist.',
},
ravn:{
 street:'Ravn',pbDesc:'Mage: Awakened, hermetic, a view into astral space',idnShort:'corporate SIN cancelled',
 look:'Mid forties, greying temples, strong polished tusks. Tweed jacket, reading glasses with a sensing focus, a ring of meteoric iron on the little finger.',
 heritage:'Europe · Kraków, transferred to Seattle on a corporate contract and stayed',
 background:'Corporate · wage mage in a corporation’s magical security: check barriers, banish spirits, do not ask questions. You asked.',
 vice:'Weird · conversations with “Vesna”, a free spirit living in the empty library at Pike Place who only answers in rhymes',
 idn:'Your corporate SIN was deleted with the dismissal. You live on a fake SIN, occupation: independent scholar.',
 friendsLabel:'Strange Friends',
 role:'Sees what nobody else sees: barriers, watchers, magical auras, the case among a hundred objects. Casts quietly and knows how corporate mages think.',
 feel:'Knowledge, astral space, spells with deliberation. You are the one who says: “Wait. There is something about this wall.”',
 sup:{attr:'Awakened · counts toward the 7 dots',gloss:'perceive astrally, read barriers and spirits'},
 metaTraits:['You can see in low light as well as if it were well lit.','Regain 1 edge when you roll a critical on a desperate action roll.','Spend 1 edge to ignore a harm penalty (including incapacitation) for an action.'],
 cyber:'No implants: every piece of chrome would weaken your magic. Your foci are glasses and ring.',
 karma:['You addressed a challenge with knowledge or magical power.'],
 abilities:[{tag:'Required',t:'Arcane method: hermetic tradition (choose drawbacks per the rulebook). You may roll the Assense action; when you roll a desperate Assense action, mark 1 karma on the Willpower track. Buy further Assense dots as a Willpower advance. Never Emergent or an adept.'},{tag:'Start',t:'You know the unique methods to activate metaplanar energies through your body to cast spells. You can Study a spell formula to summon a supernatural effect. You begin with two spells already learned.'}],
 spells:{h:'Two spells learned',list:[{n:'Stunbolt',t:'A surge of mana against a target’s mind: unconsciousness instead of wounds. Non-lethal, silent, visible only to the Awakened. Study, line of sight.'},{n:'Veil',t:'An illusion over a person or thing: different clothes, another face, a case that looks like a briefcase. Lasts as long as you concentrate. It fools people, not cameras.'}]},
 items:['The ring of meteoric iron: wield spells with exceptional control.','Glasses through which you see arcane energies in great detail. Also some protection against possession.','A small arcane amulet that astral beings prefer to avoid.','Grave dust, prayer beads, awakened feathers: concentrated essence for big spells, deteriorates after use.','An awakened animal as a companion (cohort, expert). Ravn has none; Vesna would supposedly be jealous.'],
 friend:{n:'Talia Vance, talismonger in Tacoma',t:'Deals in foci and reagents and hears everything Seattle’s Awakened gossip about. She has heard that the barrier in the Meridian Spire was drawn by a master nobody knows.'},
 rival:{n:'Dr. Henrik Solvay, Ravn’s former supervisor',t:'Still runs the magical security of the former corporation and has marked Ravn’s file “unreliable, monitor whereabouts”.'},
 why:'For twelve years you drew barriers for people who never told you what lay behind them. Now, for once, you want to know what is behind a wall built this well. The nuyen pay for Vesna’s library. The curiosity you pay yourself.',
 shine:['<b>Vault 110:</b> Assense shows you the dual mana barrier, the living tissue and the watcher on its rounds. At the doorway you see how the barrier is opened in a controlled way: an advantage for any way in of your own.','<b>The collection:</b> The case carries a faint, old aura. Among a hundred glittering things it is the only one that whispers to you. You also see which antiques are magical and which are merely expensive.','<b>Stunbolt & Veil:</b> A guard sleeps, a runner looks like staff, the case looks like a briefcase. Non-lethal, silent, exactly as Johnson demanded.'],
 lore:{h:'Hermetics, astral space and dragons',t:'Awakened mages follow traditions: hermetics treat magic as a science of formulas and circles, shamans as a relationship with spirits and mentors. Astral space is the second layer of the world, where thoughts have colors and barriers stand like walls. At the very top stand the Great Dragons: ancient, unimaginably rich, seated on corporate boards. Some walls were not built for people.'},
 gm:'Ravn recognizes the vault shell as a cultivated dual barrier: a technique that costs decades and a fortune. No corporation builds that for art. That is the trail to Veyrath without giving away the twist. Before the run Vesna told Ravn in rhymes that the tower “has a heartbeat”. The watcher reports astral activity (Alert +1) but does not attack; Ravn can distract it with Assense or stay still. Solvay is a Heat complication for after the run.',
},
};
const CREWS_EN=[
 {n:'The Invitation',t:'Mercer (Face), Kessel (Hacker), Bastion (Muscle), Ravn (Mage). In through the glass elevator, Venn in conversation, cameras under control, a shield in front of the crew and a look into astral space.'},
 {n:'The Quiet Ones',t:'Chameleon (Snake), Fizz (Punk), Hush (Adept), Kessel (Hacker). Through the garage as staff, keycard from the event office, maintenance shaft down to 110, not a shot fired.'},
 {n:'The Air Route',t:'Zephyr (Rigger), Fizz (Punk), Bastion (Muscle), Hush (Adept). Onto the roof from above, ladder and shaft, gondola to the technical airlock, skycab for the getaway.'},
 {n:'Three players',t:'Mercer, Fizz and Ravn: charm, climbing and magic. Replace Kessel’s camera work with flashbacks and Fizz’s EMP grenades.'},
];
